Repository openebs/maya, pull requests merged in 2018-10, with the labels that each got.

#533 #1914 Fix typo in util.go
  orchprovider/k8s/v1/util.go
Labels: Hacktoberfest

#537 Fix typo in jiva_volume_0.7.0.go
  pkg/install/v1alpha1/jiva_volume_0.7.0.go
Labels: Hacktoberfest

#539 Fix type in util.go
  types/v1/util.go
Labels: Hacktoberfest

#540 Fix typo in jiva_volume_delete.go
  pkg/task/v1alpha1/jiva_volume_delete.go
Labels: Hacktoberfest

#542 Fixed typo in runtask_command.go #1934
  pkg/task/v1alpha1/runtask_command.go
Labels: Hacktoberfest

#553 Fix overridden typo
  pkg/template/template.go
Labels: Hacktoberfest

#543 Fixing the lint issues in cas_template_engine.go
  pkg/engine/cas_template_engine.go
Labels: Hacktoberfest

#552 Fix lint error in iscsi.go
  cmd/maya-agent/app/command/iscsi.go
Labels: Hacktoberfest

#545 Fix lint issues in constant.go
  types/v1/constant.go
Labels: Hacktoberfest

#554 Fix separator typo
  pkg/template/template_test.go
Labels: Hacktoberfest

#560 Fix typo in handler_test.go
  cmd/maya-apiserver/spc-watcher/handler_test.go
Labels: Hacktoberfest

#565 Fixes typos
  cmd/mayactl/app/command/volume_info.go
Labels: Hacktoberfest

#550 Fix the lint issue about package comments
  pkg/storagepool/storagepool_template_engine.go
Labels: Hacktoberfest

#548 Fixes go lint in jiva.go
  volume/provisioners/jiva/jiva.go
Labels: Hacktoberfest

#561 Adding unit test for Version method
  pkg/install/v1alpha1/version_test.go
Labels: Hacktoberfest

#569 Fixes typo line 554 in cstor_volume_0.7.0.go
  pkg/install/v1alpha1/cstor_volume_0.7.0.go
Labels: Hacktoberfest

#573 Fix golint issue in controller_client.go
  pkg/client/jiva/controller_client.go
Labels: Hacktoberfest

#571 Fix golint issues in cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
Labels: Hacktoberfest

#578 Fixes golint issue in storage_pool_claim.go
  pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
Labels: Hacktoberfest

#570 Fixes golint issues
  types/v1/math.go
Labels: Hacktoberfest

#572 Fixes golint issues
  cmd/maya-agent/types/v1/storagebackend.go
Labels: Hacktoberfest

#575 Fix golint issue in file cstor_pool.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
Labels: Hacktoberfest

#580 fix golint for types/doc.go
  types/doc.go
Labels: Hacktoberfest

#588 #openebs/1954 Fix golint issues
  pkg/install/v1alpha1/template_values.go
Labels: Hacktoberfest

#585 Fix golint issue in resource.go #1957
  pkg/client/k8s/v1alpha1/resource.go
  pkg/volume/volume.go
Labels: Hacktoberfest

#582 fix golint for types/v1/envs.go
  types/v1/envs.go
Labels: Hacktoberfest

#581 Fixes linting issue in handler.go
  cmd/maya-apiserver/spc-watcher/handler.go
Labels: Hacktoberfest

#574 Fixes go lint in signal package
  pkg/signals/signal_posix.go
Labels: Hacktoberfest

#591 fix punctuation, formatting and typos in docs
  CONTRIBUTING.md
  docs/developer.md
Labels: Hacktoberfest

#592 Fix golint issue in storagepool_create.go
  cmd/maya-apiserver/spc-watcher/storagepool_create.go
  cmd/maya-apiserver/spc-watcher/storagepool_create_test.go
Labels: Hacktoberfest

#612 Fix modified env variable after tests
  pkg/snapshot/v1alpha1/snapshot_test.go
Labels: Hacktoberfest

#617 remove passing resp, req
  cmd/maya-apiserver/app/server/snapshot_endpoint_v1alpha1.go
Labels: Hacktoberfest

#634 Add tests for /maya/pkg/task/identity.go
  pkg/task/identity_test.go
Labels: Hacktoberfest

#631 Mayactl volume info command should be changed to mayactl volume describe #1990
  ci/setup_env.sh
  cmd/mayactl/app/command/volume_info.go
Labels: Hacktoberfest

#626 Fix typographical error, adhere to bash style guidelines
  buildscripts/mayactl/build.sh
Labels: Hacktoberfest

#544 Fixing the lint issues in util.go
  cmd/mayactl/app/command/volume.go
  pkg/client/jiva/controller_client.go
  pkg/client/jiva/controller_client_test.go
  pkg/client/jiva/replica_client.go
  pkg/client/mapiserver/status.go
  pkg/util/util.go
Labels: Hacktoberfest

#620 lint(issue-1992) : improved mayactl error message: fixes #1992
  cmd/mayactl/app/command/volume.go
Labels: Hacktoberfest

#579 Fixed lint errors in the volume package
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  pkg/volume/volume.go
  pkg/volume/volume_template_engine.go
Labels: Hacktoberfest

#611 Renamed volume info command to volume describe
  cmd/mayactl/app/command/volume_info.go
Labels: Hacktoberfest

#635 Fixes #1943
  pkg/task/v1alpha1/runtask_command.go
Labels: Hacktoberfest

#615 Adding capacity parameter in ebs volumes list
  cmd/mayactl/app/command/volumes_list.go
Labels: Hacktoberfest

#644 Update README - add license section and badge
  README.md
Labels: Hacktoberfest

#583 Fixed golint issue in cas_template_key.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/task/runner.go
  pkg/task/task.go
Labels: Hacktoberfest

#599 fix linting issues
  README.md
  cmd/cstor-pool-mgmt/controller/common/common.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
  cmd/maya-exporter/app/collector/jivacollector.go
  pkg/client/http/v1alpha1/http_client.go
  pkg/util/unixsock.go
Labels: Hacktoberfest

#651 Fixing golint issues in clientset.go
  pkg/client/k8s/v1alpha1/clientset.go
Labels: Hacktoberfest

#655 Fixed golint issue
  pkg/env/v1alpha1/env.go
  types/v1/policies.go
Labels: Hacktoberfest

#662 Fix #2141 golint issues area/maya
  types/v1/types.go
Labels: Hacktoberfest

#691 Fix for issue #2102
  pkg/template/query.go
Labels: Hacktoberfest

#684 Fix linting for issue 2111 - https://github.com/openebs/openebs/issue…
  pkg/client/k8s/k8s.go
Labels: Hacktoberfest

#668 Fixed Linting issue in maya/orchprovider/nomad/v1/api.go
  orchprovider/nomad/v1/api.go
  types/v1/scale_int.go
Labels: Hacktoberfest

#682 Fix linting for issue 2114
  types/v1/util.go
Labels: Hacktoberfest

#680 Fix package comment
  cmd/maya-apiserver/spc-watcher/handler.go
  cmd/maya-apiserver/spc-watcher/spc_lease_test.go
  cmd/maya-apiserver/spc-watcher/storagepool_create.go
Labels: Hacktoberfest

#697 Fix #2088 golint issue in maya/pkg/task/patch.go
  pkg/task/patch.go
Labels: Hacktoberfest

#670 Fix Golint Issues
  pkg/task/v1alpha1/store_command.go
  types/profiles/v1/doc.go
Labels: Hacktoberfest

#692 feat(mayactl): Adds bash completion for mayactl (#1987)
  cmd/mayactl/app/command/commands.go
  cmd/mayactl/app/command/completion.go
Labels: Hacktoberfest

#674 Fix golint issues
  cmd/maya-apiserver/app/server/http.go
  orchprovider/nomad/v1/nomad_plug.go
  pkg/apis/openebs.io/register.go
  pkg/apis/openebs.io/v1alpha1/disk.go
  pkg/signals/signal.go
Labels: Hacktoberfest

#683 Fix linting for issue #2100
  pkg/version/version.go
Labels: Hacktoberfest

#699 Fix #2106 go lint issues
  volume/policies/v1/policy.go
Labels: Hacktoberfest

#686 Fixed golint issues in maya/pkg/nethelper/ipcalc.go
  pkg/nethelper/ipcalc.go
Labels: Hacktoberfest, Needs-Review

#710 Fixes #2120 golint issues
  cmd/maya-apiserver/app/server/metadata_endpoint.go
Labels: Hacktoberfest, Needs-Review

#720 suffix.go: Fix golint issues
  types/v1/suffix.go
Labels: Hacktoberfest

#714 Fix spelling errors
  Gopkg.toml
  buildscripts/push
  cmd/maya-apiserver/app/config/config.go
  cmd/maya-apiserver/app/server/http.go
  cmd/maya-apiserver/app/server/http_test.go
  cmd/maya-apiserver/spc-watcher/controller.go
  cmd/maya-apiserver/spc-watcher/handler.go
  cmd/maya-apiserver/spc-watcher/handler_test.go
  cmd/maya-apiserver/spc-watcher/select_disk.go
  cmd/maya-apiserver/spc-watcher/spc_lease.go
  cmd/maya-apiserver/spc-watcher/start.go
  cmd/maya-apiserver/spc-watcher/storagepool_create.go
  cmd/maya-exporter/app/collector/cstorcollector.go
  cmd/maya-exporter/app/command/command.go
  cmd/mayactl/app/command/snapshot/snapshot.go
  cmd/mayactl/app/command/volume_info.go
  hack/cstor_volume/test/openebs-operator.yaml
  hack/cstor_volume/test/test_1/test-script.sh
  hack/cstor_volume/test/test_3/test-script.sh
  hack/cstor_volume/test/test_4/test-script.sh
  orchprovider/k8s/v1/k8s.go
  orchprovider/k8s/v1/k8s_test.go
  orchprovider/nomad/v1/nomad_plug.go
  pkg/apis/openebs.io/v1alpha1/disk.go
  pkg/apis/openebs.io/v1alpha1/register.go
  pkg/client/mapiserver/utils_test.go
  pkg/engine/cas_template_engine.go
  pkg/install/v1alpha1/cstor_sparse_pool_claim_0.7.0.go
  pkg/install/v1alpha1/jiva_volume_0.6.0.go
  pkg/nethelper/ipcalc.go
  pkg/task/v1alpha1/jiva_volume_delete.go
  pkg/task/v1alpha1/runtask_command.go
  pkg/task/v1alpha1/store_command.go
  pkg/template/template.go
  types/v1/amount.go
  types/v1/profile/orchestrator/profile.go
  types/v1/types.go
  volume/policies/v1/policy_jiva.go
  volume/policies/v1/policy_k8s.go
  volume/profiles/profiles.go
  volume/provisioners/jiva/snapshot_create.go
  volume/provisioners/jiva/snapshot_list.go
  volume/provisioners/jiva/snapshot_revert.go
Labels: Hacktoberfest

#713 [WIP]Fix #2098 golint issue in maya/types/v1/amount.go
  types/v1/amount.go
Labels: Hacktoberfest

#715 [WIP]Fix golint issue in maya/pkg/task/runner.go (openebs#2090)
  pkg/task/runner.go
Labels: Hacktoberfest

#744 Fixed golint issues in maya/pkg/apis/openebs.io/v1alpha1/cstor_volume…
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
Labels: Hacktoberfest

#725 Fix issues openebs/openebs#2099, 2104, 2105
  pkg/install/v1alpha1/env_setter.go
  pkg/task/identity.go
  pkg/task/v1alpha1/store_command.go
Labels: Hacktoberfest

#740 Fixed Go lint issues in file: policy_jiva_k8s.go
  volume/policies/v1/policy_jiva_k8s.go
Labels: Hacktoberfest

#696 Add negative test on NewMetaTaskExecutor
  pkg/task/meta_test.go
Labels: Hacktoberfest, Needs-Review

#755 fixed go-lint issue in maya/pkg/apis/openebs.io/v1alpha1/register.go
  pkg/apis/openebs.io/v1alpha1/register.go
Labels: Hacktoberfest

#712 [WIP]Fixes #2121 golint issues
  types/v1/meta.go
Labels: Hacktoberfest

#732 Adds IT for sparse-mirrored-auto(dynamic) spc with maxpool count 0 (2190)
  integration-tests/cstor-pool/cstor_integration_test.go
Labels: Hacktoberfest, Needs-Review

#736 Adds IT for sparse-mirrored-auto(dynamic) spc with maxpool count 3 (2187)
  integration-tests/cstor-pool/cstor_integration_test.go
Labels: Hacktoberfest, Needs-Review

#752 fix(cast): Fix cstor clone cast.
  pkg/install/v1alpha1/cstor_volume.go
Labels: BUG

#760 fixed typo in json tag in maya/types/v1/metrics.go
  cmd/maya-exporter/app/collector/cstorcollector_test.go
  cmd/maya-exporter/app/collector/jivacollector_test.go
  pkg/client/jiva/controller_client_test.go
  types/v1/metrics.go
Labels: Hacktoberfest, Needs-Review

#769 pool.go: Fix golint issues#1953
  cmd/cstor-pool-mgmt/pool/pool.go
Labels: Hacktoberfest

#737 Add integration test for cstor pool for sparse-mirrored-auto(dynamic)…
  integration-tests/cstor-pool/cstor_integration_test.go
Labels: Hacktoberfest, Needs-Review

#738 Fixed golint issues in maya/pkg/task/identity.go
  pkg/task/identity.go
Labels: Hacktoberfest

#733 Simplify condition using increment and decrement
  types/v1/math.go
Labels: Hacktoberfest, Needs-Review

#747 Fixed golint issues in maya/pkg/snapshot/v1alpha1/snapshot_template_e…
  pkg/snapshot/v1alpha1/snapshot_template_engine.go
Labels: Hacktoberfest, Needs-Review

#761 Running gofmt -s
  orchprovider/k8s/v1/k8s.go
  orchprovider/k8s/v1/util.go
  orchprovider/nomad/v1/helper_funcs.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
  pkg/task/v1alpha1/runtask_command_test.go
  pkg/template/template_test.go
  pkg/volume/volume_template_engine_test.go
  volume/policies/v1/policy_jiva.go
Labels: Hacktoberfest
