Repository openebs/maya, pull requests merged in 2019-07, with the labels that each got.

#1329 refact(cstor): added last update fields for cstor objects
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
Labels: needs-review, needs-upgrade-changes

#1325 feat(cvc-controller): add k8s controller for cstor volume provisioning
  Gopkg.lock
  cmd/cstorvolumeclaim/controller.go
  cmd/cstorvolumeclaim/controller_base.go
  cmd/cstorvolumeclaim/cstorvolumeclaim.go
  cmd/cstorvolumeclaim/cstorvolumedeployment.go
  cmd/cstorvolumeclaim/start.go
  cmd/maya-apiserver/app/command/start.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/cstor/volume/v1alpha1/build.go
  pkg/cstor/volumereplica/v1alpha1/build.go
  pkg/install/v1alpha1/openebs_crds.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/kubernetes/service/v1alpha1/build.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/kubernetes/pkg/util/slice/BUILD
  vendor/k8s.io/kubernetes/pkg/util/slice/slice.go
Labels: component: CSI, component: CStorVolMgmt, type: Controller

#1330 refactor(kubeclient): add singleton instance to upgraderesult kubeclient
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/client/v1alpha1/client_test.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/upgrade/result/v1alpha1/kubernetes_test.go
Labels: type: IdiomaticMaya

#1347 chore(cspc, cstor-operator): record events on cspc
  cmd/maya-apiserver/cstor-operator/cspc/controller.go
  cmd/maya-apiserver/cstor-operator/cspc/handler.go
  cmd/maya-apiserver/cstor-operator/cspc/storagepool_create.go
Labels: component: CStorOperator

#1352 feat(install): add flag to disable default config creation
  pkg/install/v1alpha1/cstor_sparse_pool_claim.go
  pkg/install/v1alpha1/cstor_sparse_pool_claim_test.go
  pkg/install/v1alpha1/env.go
  pkg/install/v1alpha1/env_setter.go
  pkg/install/v1alpha1/env_setter_test.go
  pkg/install/v1alpha1/flags.go
  pkg/install/v1alpha1/jiva_pool.go
  pkg/install/v1alpha1/localpv_sc.go
Labels: needs-helm-changes, type: Documentation

#1366 fix(cstor-operator, spc): honour cachefile value on spc yaml
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/install/v1alpha1/cstor_pool.go
  pkg/storagepool/storagepool.go
Labels: type: CherryPick-To-1.1.x

#1370 cherry-pick(cstor-operator, spc): honour cachefile value on spc yaml
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/install/v1alpha1/cstor_pool.go
  pkg/storagepool/storagepool.go
Labels: component: CStorOperator
