Repository openebs/maya, pull requests merged in 2019-03, with the labels that each got.

#919 fix(pvc deletion, webhook): add validation prior to deleting a pvc
  GNUmakefile
  Gopkg.lock
  buildscripts/admission-server/Dockerfile
  cmd/admission-server/main.go
  cmd/maya-apiserver/app/command/start.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: area/cstor-vol-mgmt, area/documentation, area/maya, needs-operator-changes, needs-upgrade

#964 refact(version): bump Version file in master branch to 0.9.0
  VERSION
Labels: area/version

#967 fix(webhook): ignore delete request for missing resource req name
  pkg/webhook/webhook.go
Labels: area/cstor-vol-mgmt, cherrypick-to-0.8.x, release-note

#965 enhance(cast engine): Add more support for operations in runtask
  pkg/client/k8s/k8s.go
  pkg/task/identity.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/castemplate, release-note-none

#968 feat(casconfig, perf, cstor): introduce ZvolWorkers, QueueDepth & Luworkers cstor volume config
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: area/casconfig, area/documentation, area/performance, cherrypick-to-0.8.x, release-note

#976 refactor(cast engine): refactor template engine to support package version
  pkg/castemplate/v1alpha1/cas_template_engine.go
  pkg/castemplate/v1alpha1/cas_template_engine_test.go
  pkg/snapshot/v1alpha1/snapshot.go
  pkg/snapshot/v1alpha1/snapshot_template_engine.go
  pkg/storagepool/storagepool.go
  pkg/storagepool/storagepool_template_engine.go
  pkg/volume/volume.go
  pkg/volume/volume_template_engine.go
  pkg/volume/volume_template_engine_test.go
Labels: area/castemplate, release-note-none

#959 fix(exporter): use camel case for replica status
  cmd/maya-exporter/app/collector/cstor_test.go
  cmd/maya-exporter/app/collector/metrics.go
  cmd/maya-exporter/app/collector/types.go
Labels: cherrypick-to-0.8.x, kind/bug-fix, release-note

#960 [TA5006] feat(exporter): add pool exporter yaml in runTask
  pkg/install/v1alpha1/cstor_pool.go
Labels: cherrypick-to-0.8.x, needs-helm-changes, needs-operator-changes, needs-upgrade, release-note

#978 feat(cast, statefulset): add support for statefulset in castemplate
  pkg/client/k8s/k8s.go
  pkg/k8s/from_yaml.go
  pkg/task/identity.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: cherrypick-to-0.8.x, release-note

#966 feat(cstor volume, sts): add cstor volume provisioning support in StatefulSet applications
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
  pkg/cstorpool/v1alpha2/cstorpool.go
  pkg/cstorpool/v1alpha2/cstorpool_test.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
  pkg/template/template.go
Labels: app/statefulset, area/cstor-vol-mgmt, area/documentation, cherrypick-to-0.8.x, release-note

#941 [TA4833] feat(exporter): Add pool and zvol metrics
  GNUmakefile
  buildscripts/exporter/Dockerfile
  cmd/cstor-pool-mgmt/controller/common/common_test.go
  cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller_test.go
  cmd/cstor-pool-mgmt/pool/pool_test.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
  cmd/maya-exporter/app/collector/metrics.go
  cmd/maya-exporter/app/collector/pool/metrics.go
  cmd/maya-exporter/app/collector/pool/pool.go
  cmd/maya-exporter/app/collector/pool/pool_test.go
  cmd/maya-exporter/app/collector/zvol/list.go
  cmd/maya-exporter/app/collector/zvol/list_test.go
  cmd/maya-exporter/app/collector/zvol/metrics.go
  cmd/maya-exporter/app/collector/zvol/zvol.go
  cmd/maya-exporter/app/collector/zvol/zvol_test.go
  cmd/maya-exporter/app/command/command.go
  cmd/maya-exporter/app/command/command_test.go
  cmd/maya-exporter/main.go
  pkg/util/exec-run.go
  pkg/version/version.go
  pkg/zpool/v1alpha1/zpool.go
  pkg/zvol/v1alpha1/zvol.go
Labels: area/monitoring, area/pool-metrics, cherrypick-to-0.8.x, needs-upgrade, release-note

#990 fix(ci): increase goroutine count to fix ci
  cmd/maya-exporter/app/collector/pool/pool_test.go
  cmd/maya-exporter/app/collector/zvol/list_test.go
Labels: area/travis

#989 fix(exporter): increase goroutine count to fix ci
  cmd/maya-exporter/app/collector/pool/pool_test.go
  cmd/maya-exporter/app/collector/zvol/list_test.go
Labels: area/travis, release-note-none

#985 feat(castemplate) : add support for remote execute of a command in a container of a pod
  Gopkg.lock
  pkg/client/k8s/k8s.go
  pkg/kubernetes/podexec/v1alpha1/podexec.go
  pkg/task/meta.go
  pkg/task/task.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
Labels: area/castemplate

#986 feat(openebs-upgrade) : Initial check in for upgrade result CR
  GNUmakefile
  pkg/apis/openebs.io/upgrade/v1alpha1/doc.go
  pkg/apis/openebs.io/upgrade/v1alpha1/register.go
  pkg/apis/openebs.io/upgrade/v1alpha1/upgraderesult.go
  pkg/apis/openebs.io/upgrade/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/clientset.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/doc.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/fake/clientset_generated.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/fake/doc.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/fake/register.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/scheme/doc.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/scheme/register.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/doc.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/fake/doc.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/fake/fake_upgrade_client.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/fake/fake_upgraderesult.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/generated_expansion.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/upgrade_client.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/clientset/internalclientset/typed/upgrade/v1alpha1/upgraderesult.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/factory.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/generic.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/interface.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/castemplate.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorpool.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolume.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolumereplica.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/disk.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/runtask.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepool.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepoolclaim.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/lister/upgrade/v1alpha1/expansion_generated.go
  pkg/client/generated/openebs.io/upgrade/v1alpha1/lister/upgrade/v1alpha1/upgraderesult.go
  pkg/client/k8s/k8s.go
  pkg/task/identity.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/upgrade

#995 enhance(travis): Adds `dep check` in travis
  buildscripts/travis-build.sh
Labels: area/travis, release-note-none

#997 Comments the unit test case to fix the travis failure
  cmd/maya-exporter/app/collector/zvol/list_test.go
Labels: kind/bug-fix

#999 [cherry-pick] fix(unit test): comments the test case to fix the travis failure (#997)
  cmd/maya-exporter/app/collector/zvol/list_test.go
Labels: kind/bug-fix, release-note-none

#1002 chore(cherrypick,mayactl): fixes application name not available (#953)
  pkg/install/v1alpha1/cstor_volume.go
Labels: kind/bug-fix, needs-upgrade, release-note

#979 feat(openebs-upgrade): add taskconfig schema in upgraderesult cr.
  pkg/apis/openebs.io/upgrade/v1alpha1/config.go
  pkg/apis/openebs.io/upgrade/v1alpha1/upgraderesult.go
  pkg/apis/openebs.io/upgrade/v1alpha1/zz_generated.deepcopy.go
Labels: area/upgrade

#1007 feat(cstorpool, toleration): adds toleration policy for cstor pool pods
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/castemplate, cherrypick-to-0.8.x

#1010 chore(cherry-pick,cstorpool): Adds toleration policy for cstor pool (#1007)
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/castemplate, release-note

#1011 enhance(BDD): Adds check for CVR health in sts bdd
  integration-tests/sts/sts_test.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
Labels: app/statefulset, area/integration-tests

#1001 feat(cast): add list support for upgrade result in cast
  pkg/client/k8s/k8s.go
  pkg/task/meta.go
  pkg/task/task.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/upgrade/result/v1alpha1/kubernetes_test.go
  pkg/upgrade/result/v1alpha1/upgraderesult.go
  pkg/upgrade/result/v1alpha1/upgraderesult_test.go
Labels: area/castemplate, area/upgrade

#1013 enhance(unstruct): adds new version of unstruct package
  pkg/unstruct/v1alpha2/interface.go
  pkg/unstruct/v1alpha2/kubernetes.go
  pkg/unstruct/v1alpha2/unstruct.go
  pkg/unstruct/v1alpha2/unstruct_test.go
Labels: area/idiomatic-maya

#1016 chore(cstor pool): cherry-pick of PR 1014
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/documentation, kind/bug-fix

#1018 fix(cstor volume): add hostpath config for target pod
  pkg/install/v1alpha1/cstor_volume.go
Labels: area/casconfig, area/castemplate, area/cstor-vol-mgmt, area/documentation

#1019 chore(cstor volume, cherry-pick): add config for target volume directory (#1018)
  pkg/install/v1alpha1/cstor_volume.go
Labels: area/casconfig, area/castemplate, area/documentation, release-note

#994 fix(cstor clone): adds validation at the time of creating cstor clones
  GNUmakefile
  Gopkg.lock
  cmd/admission-server/main.go
  pkg/apis/openebs.io/snapshot/v1alpha1/doc.go
  pkg/apis/openebs.io/snapshot/v1alpha1/register.go
  pkg/apis/openebs.io/snapshot/v1alpha1/types.go
  pkg/apis/openebs.io/snapshot/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/clientset.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/clientset_generated.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/register.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/scheme/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/scheme/register.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_snapshot_client.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_volumesnapshotdata.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/generated_expansion.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/snapshot_client.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/volumesnapshotdata.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/factory.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/generic.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/interface.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/castemplate.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorpool.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolume.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolumereplica.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/disk.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/runtask.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepool.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepoolclaim.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/expansion_generated.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/volumesnapshotdata.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: area/admission-webhook, area/volume-resize, needs-upgrade, release-note

#1008 fix(cstor-pool, sock): delete sock file before deleting for cstor-pool container
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/castemplate, area/cstor-pool-mgmt, kind/bug-fix, needs-upgrade

#1020 [chery-pick] fix(clone): adds validation at the time of creating cstor clones (#994)
  GNUmakefile
  Gopkg.lock
  cmd/admission-server/main.go
  pkg/apis/openebs.io/snapshot/v1alpha1/doc.go
  pkg/apis/openebs.io/snapshot/v1alpha1/register.go
  pkg/apis/openebs.io/snapshot/v1alpha1/types.go
  pkg/apis/openebs.io/snapshot/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/clientset.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/clientset_generated.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/fake/register.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/scheme/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/scheme/register.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/doc.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_snapshot_client.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/fake/fake_volumesnapshotdata.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/generated_expansion.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/snapshot_client.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/clientset/internalclientset/typed/snapshot/v1alpha1/volumesnapshotdata.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/factory.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/generic.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/interface.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/castemplate.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorpool.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolume.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/cstorvolumereplica.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/disk.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/runtask.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepool.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/informer/externalversions/openebs.io/v1alpha1/storagepoolclaim.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/expansion_generated.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/volumesnapshot.go
  pkg/client/generated/openebs.io/snapshot/v1alpha1/lister/snapshot/v1alpha1/volumesnapshotdata.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: needs-upgrade

#1024 cherry-pick(cstor_pool_runtask): mv spc from annotation to labels
  pkg/install/v1alpha1/cstor_pool.go
Labels: kind/bug-fix

#1027 refactor(mayactl,runtask): Removes application information from mayactl
  cmd/mayactl/app/command/volume_info.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: kind/bug-fix

#1029 chore(cherry-pick,mayactl,runtask): Removes application information from mayactl
  cmd/mayactl/app/command/volume_info.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: kind/bug-fix
