Repository openebs/maya, pull requests merged in 2019-05, with the labels that each got.

#1127 enhance(sc, idiomatic): add volumebinding mode in storageclass
  pkg/kubernetes/storageclass/v1alpha1/build.go
  pkg/kubernetes/storageclass/v1alpha1/build_test.go
Labels: area/idiomatic-maya

#1138 feat(unstruct, idiomatic): add support to get dynamic clientset using KubeConfig path
  integration-tests/artifacts/installer/v1alpha1/installer.go
  pkg/unstruct/v1alpha2/kubernetes.go
  pkg/unstruct/v1alpha2/kubernetes_test.go
Labels: area/idiomatic-maya

#1126 feat(clientset, idiomatic): add support to get clientset using KubeConfig path
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/client/v1alpha1/client_test.go
  pkg/kubernetes/node/v1alpha1/kubernetes.go
  pkg/kubernetes/node/v1alpha1/kubernetes_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
  pkg/kubernetes/storageclass/v1alpha1/kubernetes.go
  pkg/kubernetes/storageclass/v1alpha1/kubernetes_test.go
Labels: area/idiomatic-maya

#1141 feat(spc): add v1beta1 storagepoolclaim package
  pkg/storagepoolclaim/v1beta1/doc.go
  pkg/storagepoolclaim/v1beta1/kubernetes.go
  pkg/storagepoolclaim/v1beta1/storagepoolclaim.go
  pkg/storagepoolclaim/v1beta1/storagepoolclaim_test.go
  pkg/storagepoolclaim/v1beta1/validate.go
Labels: Needs-Review, area/cstor-operator, area/idiomatic-maya, area/maya

#1072 docs(idiomatic maya): add best practices guide to writing code in idiomatic maya based patterns
  docs/idiomatic-maya-guide.md
Labels: area/documentation, area/idiomatic-maya

#1047 feat(bdd, jiva) add BDD test for jiva replica pod node-stickiness
  integration-tests/artifacts/installer/v1alpha1/installer.go
  integration-tests/artifacts/openebs-ci.yaml
  integration-tests/jiva/node-stickiness/install_resource.go
  integration-tests/jiva/node-stickiness/jiva_pvc_resource.yaml
  integration-tests/jiva/node-stickiness/jiva_sc_resource.yaml
  integration-tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_suit_test.go
  integration-tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_test.go
Labels: Needs-Review, area/bdd, area/integration-tests, area/jiva

#1147 feat(maya): add v1alpha2 disk package
  pkg/disk/v1alpha2/disk.go
  pkg/disk/v1alpha2/disk_test.go
  pkg/disk/v1alpha2/doc.go
  pkg/disk/v1alpha2/kubernetes.go
Labels: Needs-Review, area/maya

#1152 feat(maya-installer): add cstorpoolcluster crd in maya installer
  pkg/install/v1alpha1/openebs_crds.go
Labels: Needs-Review, area/installer, area/maya

#1155 feat(runtask): add get and patch task operation support for cstorpoolcluster
  pkg/client/k8s/k8s.go
  pkg/task/identity.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: Needs-Review, area/castemplate

#1121 debuggability(log): remove un-required log entries
  cmd/maya-apiserver/app/server/http.go
  cmd/maya-apiserver/app/server/http_test.go
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  pkg/apis/openebs.io/v1alpha1/cas_volume_test.go
  pkg/castemplate/v1alpha1/cas_template_engine.go
  pkg/client/k8s/v1alpha1/unstructured.go
  pkg/task/meta.go
  pkg/task/meta_test.go
  pkg/task/runner.go
  pkg/task/task.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/volume/volume.go
  pkg/volume/volume_template_engine.go
Labels: area/debuggability, area/idiomatic-maya

#1095 doc(integration-tests) : update README.md with steps to trigger integration test
  integration-tests/README.md
  integration-tests/sts/sts_suite_test.go
Labels: area/bdd, area/integration-tests

#1157 debuggability (error package): change import path of error package in m-upgrade
  cmd/upgrade/app/v1alpha1/executor.go
  cmd/upgrade/app/v1alpha1/result.go
  cmd/upgrade/app/v1alpha1/upgrade.go
  pkg/errors/v1alpha1/types.go
  pkg/upgrade/v1alpha1/config.go
  pkg/upgrade/v1alpha1/config_test.go
  pkg/upgrade/v1alpha1/engine.go
  pkg/upgrade/v1alpha1/engine_test.go
Labels: area/debuggability, area/idiomatic-maya

#1153 feat(CAST, runtask): add runtask get support for service and CStor volume
  pkg/cstorvolume/v1alpha1/kubernetes.go
  pkg/kubernetes/service/v1alpha1/kubernetes.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/upgrade

#1174 fix(sts): fix target pod stuck at pending state (#1124)
  pkg/install/v1alpha1/cstor_volume.go
Labels: app/statefulset, kind/bug-fix

#1178 cherrypick(install): adds openebs.io/version label to the OpenEBS dataplane components (#1066)
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: needs-upgrade

#1173 refactor(m-upgrade): Refactor owner reference fetch logic in m-upgrade
  cmd/upgrade/app/v1alpha1/executor.go
  cmd/upgrade/app/v1alpha1/result.go
  pkg/client/k8s/k8s.go
Labels: area/upgrade

#1176 feat(runtask, CAST): add update upgrade result template function
  cmd/upgrade/app/v1alpha1/result.go
  pkg/task/task.go
  pkg/templatefuncs/v1alpha1/templatefuncs.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/upgrade/result/v1alpha1/kubernetes_test.go
  pkg/upgrade/result/v1alpha1/upgraderesult.go
  pkg/upgrade/result/v1alpha1/upgraderesult_test.go
Labels: area/castemplate, area/upgrade

#1181 fix(cstor_volume_replica) : fix cvr reconciliation when it enters in error phase
  cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
Labels: area/cstor-pool-mgmt

#1164 debuggability(log): improved logs for incorrect yaml
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  pkg/apis/openebs.io/upgrade/v1alpha1/upgraderesult.go
  pkg/client/k8s/k8s.go
  pkg/task/runner.go
  pkg/task/task.go
Labels: area/debuggability, area/idiomatic-maya

#1195 feat(backup, ark): change backup CRD names
  cmd/cstor-pool-mgmt/controller/backup-controller/handler.go
  cmd/cstor-pool-mgmt/controller/backup-controller/new_backup_controller.go
  cmd/cstor-pool-mgmt/controller/backup-controller/new_backup_controller_test.go
  cmd/cstor-pool-mgmt/controller/backup-controller/run_backup_controller.go
  cmd/cstor-pool-mgmt/controller/start-controller/controller.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  cmd/maya-apiserver/app/server/backup_endpoint_v1alpha1.go
  docs/backup_cstor.md
  pkg/apis/openebs.io/v1alpha1/cstor_backup.go
  pkg/apis/openebs.io/v1alpha1/cstor_completed_backup.go
  pkg/apis/openebs.io/v1alpha1/register.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/backupcstor.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/backupcstorlast.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/cstorbackup.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/cstorcompletedbackup.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_backupcstor.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_backupcstorlast.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_cstorbackup.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_cstorcompletedbackup.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_openebs.io_client.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/generated_expansion.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/openebs.io_client.go
  pkg/client/generated/informers/externalversions/generic.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/cstorbackup.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/cstorcompletedbackup.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/listers/openebs.io/v1alpha1/backupcstor.go
  pkg/client/generated/listers/openebs.io/v1alpha1/backupcstorlast.go
  pkg/client/generated/listers/openebs.io/v1alpha1/cstorbackup.go
  pkg/client/generated/listers/openebs.io/v1alpha1/cstorcompletedbackup.go
  pkg/client/generated/listers/openebs.io/v1alpha1/expansion_generated.go
  pkg/install/v1alpha1/openebs_crds.go
Labels: area/backup, area/integration, area/schema, needs-helm-changes, needs-operator-changes

#1196 feat(bdd, jiva) add BDD for provisioning jiva volume
  cmd/upgrade/app/v1alpha1/executor.go
  integration-tests/admission/admission_test.go
  integration-tests/framework/v1alpha1/framework.go
  integration-tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_suit_test.go
  integration-tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_test.go
  integration-tests/jiva/volume/provision_test.go
  integration-tests/jiva/volume/suite_test.go
  integration-tests/sts/sts_suite_test.go
  integration-tests/sts/sts_test.go
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/client/v1alpha1/client_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
  pkg/task/task.go
Labels: component: IntegrationTests, component: Jiva, type: BDD

#1198 debuggability(log): removes unnecessary cas object dumps for read requests
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  pkg/volume/volume.go
Labels: type: Debuggability

#1201 Chore(tests, BDD): rename integration-test to tests dir
  GNUmakefile
  buildscripts/test-cov.sh
  buildscripts/test.sh
  tests/README.md
  tests/admission/admission_suite_test.go
  tests/admission/admission_test.go
  tests/artifacts/cr-schema.yaml
  tests/artifacts/cstor-pvc.yaml
  tests/artifacts/cvr-schema.yaml
  tests/artifacts/hostdevice-pv-pod.yaml
  tests/artifacts/hostpath-pv-pod.yaml
  tests/artifacts/installer/v1alpha1/installer.go
  tests/artifacts/jiva-pvc.yaml
  tests/artifacts/openebs-ci.go
  tests/artifacts/openebs-ci.yaml
  tests/artifacts/openebs-local-provisioner.yaml
  tests/artifacts/sc-hostdevice.yaml
  tests/artifacts/sc-hostpath.yaml
  tests/artifacts/storageclass-single-replica.yaml
  tests/common/readme.md
  tests/cstor-pool/README.md
  tests/cstor-pool/cstor_integration_test.go
  tests/cstor-volume/README.md
  tests/framework/v1alpha1/framework.go
  tests/jiva/node-stickiness/install_resource.go
  tests/jiva/node-stickiness/jiva_pvc_resource.yaml
  tests/jiva/node-stickiness/jiva_sc_resource.yaml
  tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_suit_test.go
  tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_test.go
  tests/jiva/snapshot/provision_test.go
  tests/jiva/snapshot/suite_test.go
  tests/jiva/volume/provision_test.go
  tests/jiva/volume/suite_test.go
  tests/kubernetes/kubeclient.go
  tests/kubernetes/kubernetes.go
  tests/kubernetes/kubernetes_suite_test.go
  tests/kubernetes/kubernetes_test.go
  tests/operations.go
  tests/sanity/sanity_suite_test.go
  tests/sanity/sanity_test.go
  tests/sts/sts_suite_test.go
  tests/sts/sts_test.go
Labels: component: IntegrationTests, type: BDD

#1204 tests(cstorpool): add flag to take kubeconfigpath
  pkg/cstorpool/v1alpha3/kubernetes.go
  pkg/storagepoolclaim/v1alpha1/kubernetes.go
  tests/cstor-pool/cstor_integration_test.go
Labels: component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1208 refactor(apis): refactor and include new NDM APIs into Maya
  GNUmakefile
  pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
  pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
  pkg/apis/openebs.io/ndm/v1alpha1/disk_types.go
  pkg/apis/openebs.io/ndm/v1alpha1/doc.go
  pkg/apis/openebs.io/ndm/v1alpha1/register.go
  pkg/apis/openebs.io/ndm/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/clientset.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/doc.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/fake/clientset_generated.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/fake/doc.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/fake/register.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/scheme/doc.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/scheme/register.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/blockdevice.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/blockdeviceclaim.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/disk.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/doc.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/doc.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_blockdevice.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_blockdeviceclaim.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_disk.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/fake/fake_ndm_client.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/generated_expansion.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/clientset/internalclientset/typed/ndm/v1alpha1/ndm_client.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/factory.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/generic.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/interface.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/blockdevice.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/blockdeviceclaim.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/disk.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/informer/externalversions/ndm/v1alpha1/interface.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/blockdevice.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/blockdeviceclaim.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/disk.go
  pkg/client/generated/openebs.io/ndm/v1alpha1/lister/ndm/v1alpha1/expansion_generated.go
Labels: component: NDM

#1158 [WIP] feat(exporter): add bdd for pool-exporter
  pkg/apis/openebs.io/v1alpha1/cas_pool_metrics.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/cstorvolume/v1alpha1/kubernetes.go
  pkg/cstorvolume/v1alpha1/kubernetes_test.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  tests/exporter/exporter_test.go
  tests/exporter/suite_test.go
  tests/operations.go
Labels: component: Exporter, component: IntegrationTests, type: BDD, type: Monitoring

#1213 fix(logs): increased log level for regular logs
  cmd/cstor-pool-mgmt/controller/common/common.go
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/pool/pool.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
Labels: type: Debuggability

#1212 feat(cstor,BDD): Add cstor volume BDD for volume provisioning
  tests/cstor-volume/README.md
  tests/cstor/volume/provision_test.go
  tests/cstor/volume/suite_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1210 refact(bdd) added flag to take replica count as input
  tests/cstor-pool/cstor_integration_test.go
  tests/jiva/clone/provision_test.go
  tests/jiva/clone/suite_test.go
  tests/jiva/jiva.go
  tests/jiva/snapshot/provision_test.go
  tests/jiva/snapshot/suite_test.go
  tests/jiva/volume/provision_test.go
  tests/jiva/volume/suite_test.go
Labels: component: IntegrationTests, component: Jiva, type: BDD

#1209 feat(bdd, upgrade) add BDD for jiva volume upgrade
  cmd/upgrade/app/v1alpha1/result.go
  pkg/kubernetes/pod/v1alpha1/pod.go
  pkg/task/task.go
  pkg/unstruct/v1alpha2/unstruct.go
  pkg/unstruct/v1alpha2/unstruct_test.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/upgrade/result/v1alpha1/kubernetes_test.go
  pkg/upgrade/result/v1alpha1/upgraderesult.go
  pkg/upgrade/result/v1alpha1/upgraderesult_test.go
  pkg/util/http/v1alpha1/http.go
  tests/operations.go
  tests/upgrade/0.8.2-0.9.0/jiva/suite_test.go
  tests/upgrade/0.8.2-0.9.0/jiva/volume_test.go
Labels: component: IntegrationTests, component: Jiva, component: Upgrade, type: BDD, type: IdiomaticMaya

#1062 feat(bdd, jiva, -ve test) add BDD test for invalid yamls during jiva provisioning
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  tests/framework/v1alpha1/framework.go
  tests/jiva/invalidconfig/invalidconfig_test.go
  tests/jiva/invalidconfig/suite_test.go
  tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_suit_test.go
  tests/sts/sts_suite_test.go
  tests/sts/sts_test.go
Labels: component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1218 refactor(CAST, exec): refactor runtask pod exec functionality
  pkg/client/k8s/k8s.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/podexec/v1alpha1/podexec.go
  pkg/task/task.go
Labels: type: CASTemplate, type: IdiomaticMaya

#1216 refact(bdd): added check for registered jiva replica count after upgrade
  tests/upgrade/0.8.2-0.9.0/jiva/suite_test.go
  tests/upgrade/0.8.2-0.9.0/jiva/volume_test.go
Labels: component: IntegrationTests, component: Jiva, component: Upgrade, type: BDD

#1219 feat(bdd,cstor): make replica count and pool count configurable
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
  tests/cstor/cstor.go
  tests/cstor/snapshot/snapshot_test.go
  tests/cstor/snapshot/suite_test.go
  tests/cstor/volume/provision_test.go
  tests/cstor/volume/suite_test.go
  tests/operations.go
  tests/sts/sts_test.go
Labels: component: IntegrationTests, type: BDD, type: Travis

#1225 fix(stale_files): remove files related to older version of NDM CRs
  cmd/maya-apiserver/cstor-operator/spc/controller.go
  cmd/maya-apiserver/cstor-operator/spc/handler.go
  cmd/maya-apiserver/cstor-operator/spc/handler_test.go
  cmd/maya-apiserver/cstor-operator/spc/start.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
  pkg/algorithm/nodeselect/v1alpha1/config.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/disk.go
  pkg/apis/openebs.io/v1alpha1/register.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/disk.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_disk.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_openebs.io_client.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/generated_expansion.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/openebs.io_client.go
  pkg/client/generated/informers/externalversions/generic.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/disk.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/listers/openebs.io/v1alpha1/disk.go
  pkg/client/generated/listers/openebs.io/v1alpha1/expansion_generated.go
  pkg/client/k8s/k8s.go
  pkg/disk/v1alpha1/disk.go
  pkg/disk/v1alpha1/disk_test.go
  pkg/disk/v1alpha1/kubernetes_client.go
  pkg/disk/v1alpha1/kubernetes_client_test.go
  pkg/disk/v1alpha1/spc_client.go
  pkg/disk/v1alpha1/spc_client_test.go
  pkg/disk/v1alpha2/disk.go
  pkg/disk/v1alpha2/disk_test.go
  pkg/disk/v1alpha2/kubernetes.go
Labels: component: CStorOperator, component: NDM

#1220 fix(jiva): launch jiva scrub jobs in openebs ns
  pkg/install/v1alpha1/jiva_volume.go
  pkg/version/kubernetes/version_test.go
Labels: BUG, component: Jiva, component: Scrub, type: Installer

#1224 feat(cstor, BDD): add tests for cstor volume clone provisioning
  tests/cstor/clone/clone_test.go
  tests/cstor/clone/suite_test.go
Labels: component: CStorVolMgmt, component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1221 feat(bdd, deploy): BDD to launch an application
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
  pkg/task/task.go
  tests/kubernetes/deployment/app_test.go
  tests/kubernetes/deployment/suite_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD
