Repository openebs/maya, pull requests merged in 2019-04, with the labels that each got.

#992 feat(cast engine): add roll out status support using runtask
  pkg/kubernetes/daemonset/v1alpha1/daemonset.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/kubernetes.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/rollout_status.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/castemplate, area/upgrade

#1021 enhance(unstruct): add list support in unstruct package
  pkg/unstruct/v1alpha2/unstruct.go
  pkg/unstruct/v1alpha2/unstruct_test.go
Labels: area/idiomatic-maya

#1035 fix(pool exporter, revert): remove pool exporter yaml in runTask
  pkg/install/v1alpha1/cstor_pool.go
Labels: kind/bug-fix

#1034 enhance(cast engine): add replicaset get list delete actions
  pkg/client/k8s/k8s.go
  pkg/kubernetes/replicaset/v1alpha1/kubernetes.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/castemplate, area/upgrade

#1039 chore(maya): enable graceful shutdown of apiserver
  cmd/maya-apiserver/app/config/config.go
Labels: area/integration-tests, area/maya

#1040 revert(exporter): remove pool exporter yaml in RunTask
  pkg/install/v1alpha1/cstor_pool.go
Labels: kind/bug-fix

#1045 revert(mayactl, runtask): remove application information from mayactl and runtask
  cmd/mayactl/app/command/volume_info.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: kind/bug-fix

#1041 refact(cast engine): add get castemplate support
  pkg/castemplate/v1alpha1/kubernetes.go
  pkg/castemplate/v1alpha1/kubernetes_test.go
Labels: area/castemplate, area/upgrade

#1044 fix(exporter, cherrypick): use camel case for replica status (#959)
  cmd/maya-exporter/app/collector/cstor_test.go
  cmd/maya-exporter/app/collector/metrics.go
  cmd/maya-exporter/app/collector/types.go
Labels: kind/bug-fix

#1025 feat(patch, upgrade-result): add patch and create support for upgrade result custom resource
  pkg/kubernetes/patch/v1alpha1/patch.go
  pkg/kubernetes/patch/v1alpha1/patch_test.go
  pkg/task/meta.go
  pkg/task/task.go
  pkg/upgrade/result/v1alpha1/kubernetes.go
  pkg/upgrade/result/v1alpha1/kubernetes_test.go
  pkg/upgrade/result/v1alpha1/upgraderesult.go
  pkg/upgrade/result/v1alpha1/upgraderesult_test.go
Labels: area/idiomatic-maya, area/upgrade

#1048 fix(installer): improve error handling during installation of resources
  pkg/client/k8s/v1alpha1/resource.go
Labels: area/installer, kind/bug-fix

#1049 feat(BDD, suite): add installer package for integration test suites
  Gopkg.lock
  integration-tests/artifacts/installer/v1alpha1/installer.go
  pkg/catalog/v1alpha1/kubernetes.go
  pkg/catalog/v1alpha1/kubernetes_test.go
  pkg/catalog/v1alpha1/unstruct.go
  pkg/kubeassert/v1alpha1/kubernetes.go
  pkg/kubernetes/client/v1alpha2/client.go
  pkg/openebscluster/v1alpha1/kubernetes.go
  pkg/unstruct/v1alpha1/kubernetes.go
  pkg/unstruct/v1alpha1/unstruct.go
  pkg/unstruct/v1alpha1/unstruct_test.go
  pkg/unstruct/v1alpha2/interface.go
  pkg/unstruct/v1alpha2/kubernetes.go
  pkg/unstruct/v1alpha2/pathvalue.go
  pkg/unstruct/v1alpha2/unstruct.go
Labels: area/debuggability, area/idiomatic-maya, area/integration-tests

#1053 chore(golangci, lint): add golangci lint aggregator
  .golangci.yml
Labels: area/code-lint, area/idiomatic-maya

#1058 refactor(makefile, docs): bumped version of go in developer docs & changes to makefile
  GNUmakefile
  docs/developer.md
Labels: area/documentation

#1057 refact(cast engine): refactor crud operations on runtask
  pkg/runtask/v1beta1/kubernetes.go
  pkg/runtask/v1beta1/kubernetes_client.go
  pkg/runtask/v1beta1/kubernetes_client_test.go
  pkg/runtask/v1beta1/kubernetes_test.go
Labels: area/castemplate, area/idiomatic-maya

#1073 fix(cstor, pool): fix scopelint errors in cstorpool
  pkg/cstorpool/v1alpha2/cstorpool.go
  pkg/cstorpool/v1alpha2/cstorpool_test.go
Labels: area/debuggability, area/idiomatic-maya, kind/bug-fix

#1071 fix(cstorvolumereplica): pin variables to avoid scope related issues
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
Labels: area/debuggability, area/idiomatic-maya, kind/bug-fix

#1054 feat(upgrade): add upgrade job
  GNUmakefile
  Gopkg.lock
  buildscripts/upgrade/Dockerfile
  cmd/upgrade/app/v1alpha1/executor.go
  cmd/upgrade/app/v1alpha1/upgrade.go
  cmd/upgrade/main.go
  pkg/apis/openebs.io/upgrade/v1alpha1/config.go
  pkg/apis/openebs.io/upgrade/v1alpha1/upgraderesult.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/apis/stringer/v1alpha1/stringer.go
  pkg/upgrade/v1alpha1/config.go
  pkg/upgrade/v1alpha1/config_test.go
  pkg/upgrade/v1alpha1/engine.go
  pkg/upgrade/v1alpha1/engine_test.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: area/debuggability, area/idiomatic-maya, area/upgrade

#1074 fix(bch, config): rename bettercodehub.yml to .bettercodehub.yml
  .bettercodehub.yml
  bettercodehub.yml
Labels: area/code-lint, area/idiomatic-maya

#1066 feat(install, cas templates): adds openebs.io/version label to the OpenEBS dataplane components
  pkg/install/v1alpha1/cstor_pool.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: area/castemplate, area/version, needs-upgrade

#1078 fix(runtask): fix storagepool runtask to have ownerreference to csp
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/documentation, kind/bug-fix, needs-upgrade

#1077 fix(pod, lint): fix scopelint errors in pod package
  pkg/kubernetes/pod/v1alpha1/pod.go
  pkg/kubernetes/pod/v1alpha1/pod_test.go
Labels: area/code-lint, area/idiomatic-maya, kind/bug-fix

#1060 chore(debuggability, idiomatic): add improved error handling
  GNUmakefile
  Gopkg.lock
  cmd/maya-apiserver/app/config/config.go
  cmd/maya-apiserver/app/config/config_parse.go
  cmd/maya-apiserver/app/config/config_test.go
  cmd/maya-apiserver/app/server/http.go
  cmd/maya-apiserver/app/server/http_test.go
  cmd/maya-apiserver/app/server/metadata_endpoint.go
  cmd/maya-apiserver/app/server/metadata_endpoint_test.go
  cmd/maya-apiserver/app/server/pool_endpoint_v1alpha1.go
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1_test.go
  pkg/apis/openebs.io/v1alpha1/cas_template.go
  pkg/apis/openebs.io/v1alpha1/cas_template_test.go
  pkg/apis/openebs.io/v1alpha1/cas_volume.go
  pkg/apis/openebs.io/v1alpha1/cas_volume_test.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool_test.go
  pkg/apis/stringer/v1alpha1/stringer.go
  pkg/castemplate/v1alpha1/cas_template_engine.go
  pkg/template/template.go
  pkg/volume/volume.go
  pkg/volume/volume_template_engine.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
Labels: area/debuggability, area/idiomatic-maya

#1080 Cherry-pick (fix, runtask): fix storagepool runtask to have ownerreference to csp (#1078)
  pkg/install/v1alpha1/cstor_pool.go
Labels: area/cstor-operator, area/cstor-pool-mgmt, area/garbage-collection

#1069 feat(upgrade): add support to build upgrade result cr.
  pkg/kubernetes/objectmeta/v1alpha1/objectmeta.go
  pkg/kubernetes/objectmeta/v1alpha1/objectmeta_test.go
  pkg/kubernetes/ownerreference/v1alpha1/ownerreference.go
  pkg/kubernetes/ownerreference/v1alpha1/ownerreference_test.go
  pkg/kubernetes/typemeta/v1alpha1/typemeta.go
  pkg/kubernetes/typemeta/v1alpha1/typemeta_test.go
  pkg/upgrade/result/v1alpha1/upgraderesult.go
  pkg/upgrade/result/v1alpha1/upgraderesult_test.go
Labels: area/idiomatic-maya, area/upgrade

#1084 fix(stringer, debuggability): remove cyclic calls in stringer package
  pkg/apis/stringer/v1alpha1/stringer.go
  pkg/apis/stringer/v1alpha1/stringer_test.go
Labels: area/debuggability, area/idiomatic-maya, kind/bug-fix

#1055 feat(node, idiomatic): add node support as per idiomatic maya guidelines
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/client/v1alpha1/client_test.go
  pkg/kubernetes/node/v1alpha1/kubernetes.go
  pkg/kubernetes/node/v1alpha1/kubernetes_test.go
  pkg/kubernetes/node/v1alpha1/node.go
  pkg/kubernetes/node/v1alpha1/node_test.go
Labels: area/idiomatic-maya

#1086 refactor(cast, deployment, rollout status): refactor rollout status code of deployment
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/rollout_status.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/kubernetes.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/rollout_status.go
  pkg/task/identity.go
  pkg/task/meta.go
Labels: area/idiomatic-maya, area/upgrade

#1083 refactor(cstor-operator,pool-mgmt,maya,mayactl): deprecate SP resource
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/controller/pool-controller/handler_test.go
  cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller_test.go
  cmd/cstor-pool-mgmt/pool/pool.go
  cmd/cstor-pool-mgmt/pool/pool_test.go
  cmd/maya-apiserver/app/server/pool_endpoint_v1alpha1.go
  cmd/maya-apiserver/cstor-operator/controller.go
  cmd/maya-apiserver/cstor-operator/controller_test.go
  cmd/maya-apiserver/cstor-operator/handler.go
  cmd/maya-apiserver/cstor-operator/handler_test.go
  cmd/maya-apiserver/cstor-operator/runner.go
  cmd/maya-apiserver/cstor-operator/runner_test.go
  cmd/maya-apiserver/cstor-operator/select_disk.go
  cmd/maya-apiserver/cstor-operator/select_disk_test.go
  cmd/maya-apiserver/cstor-operator/start.go
  cmd/maya-apiserver/cstor-operator/storagepool_create.go
  cmd/maya-apiserver/cstor-operator/storagepool_create_test.go
  cmd/mayactl/app/command/pool/describe.go
  cmd/mayactl/app/command/pool/list.go
  pkg/algorithm/nodeselect/v1alpha1/config.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
  pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/client/k8s/k8s.go
  pkg/client/mapiserver/pool.go
  pkg/install/v1alpha1/cstor_pool.go
  pkg/install/v1alpha1/storage_pool.go
  pkg/storagepool/storagepool.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: area/cstor-operator, area/cstor-pool-mgmt, area/documentation, area/idiomatic-maya, area/maya, area/mayactl, breaking-changes, needs-upgrade

#1100 fix(lint):fix errcheck in admission-server
  cmd/admission-server/main.go
Labels: area/code-lint, area/debuggability, area/idiomatic-maya

#1103 cherry-pick(lint, v0.9.x): fix lint errors
  GNUmakefile
  docs/developer.md
  pkg/cstorpool/v1alpha2/cstorpool.go
  pkg/cstorpool/v1alpha2/cstorpool_test.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
  pkg/kubernetes/pod/v1alpha1/pod.go
  pkg/kubernetes/pod/v1alpha1/pod_test.go
Labels: area/code-lint

#1104 fix(lint): fix ineffectual assignment issues in cmd
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  cmd/maya-apiserver/cstor-operator/spc_lease.go
Labels: area/code-lint

#1102 feat(pod, idiomatic) add support for pod get and delete operations
  pkg/kubernetes/pod/v1alpha1/buildlist.go
  pkg/kubernetes/pod/v1alpha1/buildlist_test.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
  pkg/kubernetes/pod/v1alpha1/pod.go
  pkg/kubernetes/pod/v1alpha1/pod_test.go
Labels: Needs-Review, area/idiomatic-maya

#1089 feat(upgrade): Create upgrade result CR
  cmd/upgrade/app/v1alpha1/executor.go
  cmd/upgrade/app/v1alpha1/result.go
  pkg/kubernetes/objectmeta/v1alpha1/objectmeta.go
  pkg/kubernetes/objectmeta/v1alpha1/objectmeta_test.go
  pkg/upgrade/v1alpha1/engine.go
  pkg/upgrade/v1alpha1/engine_test.go
Labels: area/upgrade

#1108 feat(travis, integration-test): Include integration-test package in travis unit test
  GNUmakefile
  buildscripts/test-cov.sh
  integration-tests/framework/v1alpha1/framework.go
  integration-tests/sanity/sanity_suite_test.go
  integration-tests/sts/sts_suite_test.go
  integration-tests/sts/sts_test.go
Labels: area/code-lint, area/integration-tests

#1087 fix(lint):fix unused func param and result issues in pkg
  pkg/castemplate/v1alpha1/cas_template_engine.go
  pkg/client/mapiserver/utils.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/kubernetes/deployment/extnv1beta1/v1alpha1/deployment.go
Labels: area/code-lint, area/debuggability, area/idiomatic-maya, kind/bug-fix

#1085 fix(lint): fix ineffectual assignment issues in pkg
  pkg/lease/v1alpha1/csp_lease.go
  pkg/lease/v1alpha1/csp_lease_test.go
  pkg/template/template.go
Labels: area/code-lint, area/debuggability, kind/bug-fix

#1090 feat(debuggability): custom error package for wrapping error(s)
  pkg/errors/v1alpha1/errors.go
  pkg/errors/v1alpha1/errors_test.go
  pkg/errors/v1alpha1/types.go
Labels: area/debuggability, area/idiomatic-maya

#1101 feat(pvc, idiomatic): add idiomatic support to pvc object
  integration-tests/sts/sts_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/build.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/build_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/persistentvolumeclaim.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/persistentvolumeclaim_test.go
Labels: Needs-Review, area/idiomatic-maya

#1088 feat(storageclass, idiomatic): add storageclass support as per idiomatic maya guidelines
  integration-tests/sts/sts_test.go
  pkg/kubernetes/storageclass/v1alpha1/build.go
  pkg/kubernetes/storageclass/v1alpha1/build_test.go
  pkg/kubernetes/storageclass/v1alpha1/buildlist.go
  pkg/kubernetes/storageclass/v1alpha1/buildlist_test.go
  pkg/kubernetes/storageclass/v1alpha1/kubernetes.go
  pkg/kubernetes/storageclass/v1alpha1/kubernetes_test.go
  pkg/kubernetes/storageclass/v1alpha1/storageclass.go
  pkg/kubernetes/storageclass/v1alpha1/storageclass_test.go
Labels: Needs-Review, area/idiomatic-maya

#1114 feat(cstor-operator): remove unused field from spc resource
  pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
Labels: Needs-Review, area/cstor-operator
