Repository openebs/maya, pull requests merged in 2019-01, with the labels that each got.

#867 [US3990]refactor:(cstor-operator): refactor cstor operator
  cmd/maya-apiserver/spc-watcher/handler.go
  cmd/maya-apiserver/spc-watcher/handler_test.go
  cmd/maya-apiserver/spc-watcher/select_disk.go
  cmd/maya-apiserver/spc-watcher/select_disk_test.go
  cmd/maya-apiserver/spc-watcher/storagepool_create.go
  cmd/maya-apiserver/spc-watcher/storagepool_create_test.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/install/v1alpha1/cstor_pool.go
  pkg/storagepool/storagepool.go
Labels: area/cstor-operator, enhancement, release-note, size/L

#880 enhance(cstor_volume): add toleration time of 30s in cstor target deployment
  pkg/install/v1alpha1/cstor_volume.go
Labels: Needs-Review, area/maya

#884 [US4131]fix(cstor_operator): add all disk on node for pool provisioning
  cmd/maya-apiserver/spc-watcher/select_disk.go
  cmd/maya-apiserver/spc-watcher/select_disk_test.go
Labels: BUG, Needs-Review, area/cstor-operator, priority/high

#886 feat(provision): adds SC annotation to openebs volume components
  pkg/install/v1alpha1/cstor_volume.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: Needs-Review, area/maya, enhancement

#896 feat(idiomatic_maya):refactor cstor-operator in idiomatic way -drop1
  cmd/maya-apiserver/app/command/start.go
  cmd/maya-apiserver/cstor-operator/controller.go
  cmd/maya-apiserver/cstor-operator/controller_test.go
  cmd/maya-apiserver/cstor-operator/handler.go
  cmd/maya-apiserver/cstor-operator/handler_test.go
  cmd/maya-apiserver/cstor-operator/lease.go
  cmd/maya-apiserver/cstor-operator/runner.go
  cmd/maya-apiserver/cstor-operator/runner_test.go
  cmd/maya-apiserver/cstor-operator/select_disk.go
  cmd/maya-apiserver/cstor-operator/select_disk_test.go
  cmd/maya-apiserver/cstor-operator/spc_lease.go
  cmd/maya-apiserver/cstor-operator/spc_lease_test.go
  cmd/maya-apiserver/cstor-operator/start.go
  cmd/maya-apiserver/cstor-operator/start_test.go
  cmd/maya-apiserver/cstor-operator/storagepool_create.go
  cmd/maya-apiserver/cstor-operator/storagepool_create_test.go
  cmd/maya-apiserver/cstor-operator/storagepool_delete.go
  pkg/algorithm/nodeSelect/v1alpha1/config.go
  pkg/algorithm/nodeSelect/v1alpha1/select_node.go
  pkg/algorithm/nodeSelect/v1alpha1/select_node_test.go
  pkg/client/k8s/k8s.go
  pkg/cstorpool/v1alpha1/cstorpool.go
  pkg/cstorpool/v1alpha1/kubernetes_client.go
  pkg/cstorpool/v1alpha1/kubernetes_client_test.go
  pkg/disk/v1alpha1/disk.go
  pkg/disk/v1alpha1/disk_test.go
  pkg/disk/v1alpha1/kubernetes_client.go
  pkg/disk/v1alpha1/kubernetes_client_test.go
  pkg/disk/v1alpha1/spc_client.go
  pkg/disk/v1alpha1/spc_client_test.go
  pkg/sp/v1alpha1/kubernetes_client.go
  pkg/sp/v1alpha1/kubernetes_client_test.go
  pkg/sp/v1alpha1/storagepool.go
Labels: WIP, area/cstor-operator, area/maya, enhancement, size/L
