Repository openebs/maya, pull requests merged in 2019-12, with the labels that each got.

#1533 fix(upgrade): improve logs and pre-upgrade checks
  cmd/upgrade/executor/cstor_spc.go
  cmd/upgrade/executor/cstor_volume.go
  cmd/upgrade/executor/jiva_volume.go
  cmd/upgrade/executor/options.go
  cmd/upgrade/executor/setup_job.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  pkg/upgrade/upgrader/csp_upgrade.go
  pkg/upgrade/upgrader/cstor_volume_upgrade.go
  pkg/upgrade/upgrader/exec.go
  pkg/upgrade/upgrader/helper.go
  pkg/upgrade/upgrader/jiva_upgrade.go
  pkg/upgrade/upgrader/spc_upgrade.go
  pkg/upgrade/v1alpha2/kubernetes.go
Labels: release-note-none

#1540 feat(disk replacement, cspc): add feat to support disk replacement in CSPC Operator
  cmd/cspc-operator/app/operations.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool_instance.go
Labels: component: CStorOperator

#1541 feat(blockdevice_replacment): add validation webhook for blockdevice replacement
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
  pkg/webhook/bd_replacement.go
  pkg/webhook/bd_replacement_test.go
  pkg/webhook/cspc.go
Labels: component: admission-server

#1547 chore(bd_replalcment): fix bd replacement validation bug
  pkg/webhook/bd_replacement.go
Labels: BUG, component: admission-server

#1548 fix(bd_replalcment): cherry pick validation bug fix PR (#1547)
  pkg/webhook/bd_replacement.go
Labels: component: admission-server

#1544 fix(cstor-pool-mgmt): fix livenessprobe in cStor pool deployment
  pkg/install/v1alpha1/cstor_pool.go
Labels: component: CStorPoolMgmt, needs-upgrade-changes

#1546 fix(cspi): add timeout seconds in zfs cmd used for liveness probe and safe-evict annotation on CSP
  cmd/cspc-operator/app/storagepool_create.go
  pkg/install/v1alpha1/cstor_pool.go
Labels: needs-upgrade-changes

#1549 feat(cspc): add capability to pass tolerations to pool pods via cspc
  cmd/cspc-operator/app/storagepool_create.go
  pkg/algorithm/nodeselect/v1alpha2/build_csp.go
  pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/kubernetes/podtemplatespec/v1alpha1/podtemplatespec.go
Labels: component: CStorOperator

#1567 refact(cspc): add schema for auxResource in poolConfig
  cmd/cspc-operator/app/storagepool_create.go
  pkg/algorithm/nodeselect/v1alpha2/build_csp.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool_instance.go
  pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/cstor/poolinstance/v1alpha3/build.go
Labels: release-note

#1559 refact(cvc): move cvc operator to its own deployment
  GNUmakefile
  buildscripts/cvc-operator/Dockerfile
  buildscripts/cvc-operator/Dockerfile.arm64
  buildscripts/cvc-operator/Makefile.mk
  cmd/cvc-operator/controller/controller_base.go
  cmd/cvc-operator/controller/cstorvolumeclaim.go
  cmd/cvc-operator/controller/cstorvolumedeployment.go
  cmd/cvc-operator/controller/cvc_controller.go
  cmd/cvc-operator/controller/cvc_controller_test.go
  cmd/cvc-operator/controller/start.go
  cmd/cvc-operator/main.go
  cmd/maya-apiserver/app/command/start.go
Labels: component: CSI, component: CStorOperator, enhancement, release-note-none

#1571 fix(provisioner,localpv): add SA while creating cleanup pod
  cmd/provisioner-localpv/app/provisioner_hostpath.go
Labels: release-note
