Repository openebs/maya, pull requests merged in 2019-06, with the labels that each got.

#1229 fix(install): install BlockDevice and BlockDeviceClaim CRDs
  pkg/install/v1alpha1/openebs_crds.go
Labels: component: NDM, type: Installer

#1226 refactor(localpv): change volume source from hostpath to local
  cmd/provisioner-localpv/app/helper.go
  cmd/provisioner-localpv/app/helperpod_opts.go
  cmd/provisioner-localpv/app/provisioner.go
  cmd/provisioner-localpv/app/provisioner_test.go
  pkg/kubernetes/persistentvolume/v1alpha1/build.go
  pkg/kubernetes/persistentvolume/v1alpha1/build_test.go
  pkg/kubernetes/pod/v1alpha1/build.go
Labels: component: LocalPV, type: IdiomaticMaya

#1222 feat(pool_config): store pool API struct and backend config in-core
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/pool/pool.go
  pkg/apis/openebs.io/zpool/v1alpha1/pool_topology.go
Labels: component: CStorPoolMgmt, type: Schema

#1233 fix(logs): increase log level or remove periodic logs in success path of pool and vol mgmt
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
  cmd/cstor-pool-mgmt/controller/pool-controller/run_pool_controller.go
  cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
  cmd/cstor-volume-mgmt/controller/volume-controller/new_volume_controller.go
  cmd/cstor-volume-mgmt/controller/volume-controller/run_volume_controller.go
Labels: type: Debuggability

#1234 chore(log, debuggability): reduce flooding of install logs
  pkg/install/v1alpha1/env.go
  pkg/install/v1alpha1/env_setter.go
  pkg/install/v1alpha1/installer.go
  pkg/install/v1alpha1/marshall.go
  pkg/install/v1alpha1/registrar.go
Labels: type: Debuggability

#1230 feat(bdd,-ve,cstor) BDD for negative test cases for cstor
  pkg/kubernetes/namespace/v1alpha1/namespace.go
  pkg/kubernetes/storageclass/v1alpha1/build.go
  pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
  tests/cstor/pool/negative/invalid_config_test.go
  tests/cstor/pool/negative/invalid_storageclass_test.go
  tests/cstor/pool/negative/suite_test.go
  tests/operations.go
Labels: component: CStorOperator, component: IntegrationTests, type: BDD

#1241 feat(gitlab-ci): Add openshift platform to mdap ci for v1.0.x branch
  .gitlab-ci.yml
Labels: type: Gitlab

#1243 :tada: chore(version): bump version to 1.1.0
  VERSION
Labels: type: Version

#1240 chore(log, install): add log for successful installation of resources
  cmd/maya-apiserver/app/command/start.go
Labels: type: Debuggability

#1227 feat(cstor, blockdevice): add support to use blockdevice during manual provisioning of pool creation
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  cmd/cstor-pool-mgmt/pool/pool.go
  cmd/cstor-pool-mgmt/pool/pool_test.go
  cmd/maya-apiserver/cstor-operator/spc/controller.go
  cmd/maya-apiserver/cstor-operator/spc/handler.go
  cmd/maya-apiserver/cstor-operator/spc/handler_test.go
  cmd/maya-apiserver/cstor-operator/spc/start.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
  pkg/algorithm/nodeselect/v1alpha1/config.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
  pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/apis/openebs.io/v1alpha1/cas_template_keys.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
  pkg/apis/openebs.io/v1alpha1/register.go
  pkg/apis/openebs.io/v1alpha1/storage_pool.go
  pkg/apis/openebs.io/v1alpha1/storage_pool_claim.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/blockdevice/v1alpha1/blockdevice.go
  pkg/blockdevice/v1alpha1/blockdevice_test.go
  pkg/blockdevice/v1alpha1/kubernetes_client.go
  pkg/blockdevice/v1alpha1/kubernetes_client_test.go
  pkg/blockdevice/v1alpha1/spc_client.go
  pkg/blockdevice/v1alpha1/spc_client_test.go
  pkg/client/k8s/k8s.go
  pkg/disk/v1alpha1/disk.go
  pkg/disk/v1alpha1/disk_test.go
  pkg/disk/v1alpha1/kubernetes_client_test.go
  pkg/disk/v1alpha1/spc_client.go
  pkg/disk/v1alpha1/spc_client_test.go
  pkg/disk/v1alpha2/disk.go
  pkg/disk/v1alpha2/disk_test.go
  pkg/disk/v1alpha2/doc.go
  pkg/disk/v1alpha2/kubernetes.go
  pkg/install/v1alpha1/cstor_pool.go
  pkg/storagepool/storagepool.go
  pkg/task/identity.go
  pkg/task/meta.go
  pkg/task/task.go
Labels: component: CStorOperator, component: NDM, needs-upgrade-changes, type: Documentation, type: ManualPoolProvisioning

#1239 Refact(BDD,admission): update admission BDD tests
  tests/admission/admission_suite_test.go
  tests/admission/admission_test.go
  tests/admission/suite_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1236 feat(bd, bdc, idiomatic): add blockdevice and blockdeviceclaim support as per idiomatic maya guide lines
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  pkg/algorithm/nodeselect/v1alpha1/config.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/blockdevice/v1alpha1/blockdevice.go
  pkg/blockdevice/v1alpha2/blockdevice.go
  pkg/blockdevice/v1alpha2/build.go
  pkg/blockdevice/v1alpha2/buildlist.go
  pkg/blockdevice/v1alpha2/kubernetes.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
  pkg/blockdeviceclaim/v1alpha1/build.go
  pkg/blockdeviceclaim/v1alpha1/buildlist.go
  pkg/blockdeviceclaim/v1alpha1/kubernetes.go
Labels: component: NDM, type: IdiomaticMaya

#1248 feat(runtask, priviledged) replica deployment runtask for scheduling replica pod on openshift
  pkg/install/v1alpha1/jiva_volume.go
Labels: type: CASTemplate, type: Privileged

#1245 cherry-pick(log, install): add log for successful installation of resources (#1240)
  cmd/maya-apiserver/app/command/start.go
Labels: type: CherryPick-To-1.0.x, type: Debuggability

#1242 refact(bdd, jiva): added generateName field to all clusterscope objects
  tests/jiva/clone/provision_test.go
  tests/jiva/clone/suite_test.go
  tests/jiva/snapshot/provision_test.go
  tests/jiva/snapshot/suite_test.go
  tests/jiva/volume/provision_test.go
  tests/jiva/volume/suite_test.go
Labels: component: Jiva, type: BDD

#1012 refactor(idiomatic-maya, exporter): pool exporter changes to align with idiomatic maya practices
  cmd/maya-exporter/app/collector/pool/metrics.go
  cmd/maya-exporter/app/collector/pool/pool.go
  cmd/maya-exporter/app/collector/pool/pool_test.go
  cmd/maya-exporter/app/collector/types.go
  cmd/maya-exporter/app/collector/zvol/list.go
  cmd/maya-exporter/app/collector/zvol/list_test.go
  cmd/maya-exporter/app/collector/zvol/metrics.go
  cmd/maya-exporter/app/collector/zvol/zvol.go
  cmd/maya-exporter/app/collector/zvol/zvol_test.go
  cmd/maya-exporter/app/command/command.go
  pkg/exec/mock/v1alpha1/mock.go
  pkg/exec/types.go
  pkg/exec/v1alpha1/exec.go
  pkg/prometheus/exporter/mock/v1alpha1/mock.go
  pkg/zpool/v1alpha1/zpool.go
  pkg/zvol/v1alpha1/zvol.go
Labels: component: IntegrationTests, type: IdiomaticMaya

#1246 chore(BDD): refactor cstor volume,snapshot and clone to use generate name
  tests/cstor/clone/clone_test.go
  tests/cstor/clone/suite_test.go
  tests/cstor/snapshot/snapshot_test.go
  tests/cstor/snapshot/suite_test.go
  tests/cstor/volume/provision_test.go
  tests/cstor/volume/suite_test.go
Labels: component: IntegrationTests, type: BDD

#1235 chore(operator): update artifacts operator yaml with latest changes
  tests/artifacts/openebs-ci.yaml
Labels: component: IntegrationTests, type: BDD, type: Travis

#1215 feat(cstor, csi, BDD): add integration test for cstor volume provisioning via CSI
  tests/csi/cstor/volume/provision_test.go
  tests/csi/cstor/volume/suite_test.go
  tests/cstor/clone/clone_test.go
Labels: component: CSI, component: IntegrationTests, type: BDD

#1251 fix(builder, bdc): fix builder pattern to build blockdevice claim
  pkg/blockdeviceclaim/v1alpha1/build.go
Labels: component: NDM, type: IdiomaticMaya

#1247 refact(bdd, jiva): refactored node stickiness bdd test
  pkg/kubernetes/pod/v1alpha1/pod.go
  tests/jiva/jiva.go
  tests/jiva/node-stickiness/install_resource.go
  tests/jiva/node-stickiness/jiva_pvc_resource.yaml
  tests/jiva/node-stickiness/jiva_sc_resource.yaml
  tests/jiva/node-stickiness/node_stickiness_test.go
  tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_suit_test.go
  tests/jiva/node-stickiness/replicadeletion/jiva_replica_deletion_test.go
  tests/jiva/node-stickiness/suite_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD, type: IdiomaticMaya

#1252 cherry-pick(idiomatic-maya, exporter): pool exporter changes
  cmd/maya-exporter/app/collector/pool/metrics.go
  cmd/maya-exporter/app/collector/pool/pool.go
  cmd/maya-exporter/app/collector/pool/pool_test.go
  cmd/maya-exporter/app/collector/types.go
  cmd/maya-exporter/app/collector/zvol/list.go
  cmd/maya-exporter/app/collector/zvol/list_test.go
  cmd/maya-exporter/app/collector/zvol/metrics.go
  cmd/maya-exporter/app/collector/zvol/zvol.go
  cmd/maya-exporter/app/collector/zvol/zvol_test.go
  cmd/maya-exporter/app/command/command.go
  pkg/exec/mock/v1alpha1/mock.go
  pkg/exec/types.go
  pkg/exec/v1alpha1/exec.go
  pkg/prometheus/exporter/mock/v1alpha1/mock.go
  pkg/zpool/v1alpha1/zpool.go
  pkg/zvol/v1alpha1/zvol.go
Labels: component: Exporter, type: CherryPick-To-1.0.x

#1253 feat(localpv): initial commit for block device support
  cmd/provisioner-localpv/app/config.go
  cmd/provisioner-localpv/app/helper_blockdevice.go
  cmd/provisioner-localpv/app/helper_hostpath.go
  cmd/provisioner-localpv/app/helperpod_opts.go
  cmd/provisioner-localpv/app/provisioner.go
  cmd/provisioner-localpv/app/provisioner_blockdevice.go
  cmd/provisioner-localpv/app/provisioner_hostpath.go
  pkg/install/v1alpha1/localpv_sc.go
  tests/artifacts/hostdevice-pv-pod.yaml
  tests/artifacts/sc-hostdevice.yaml
Labels: component: LocalPV

#1256 fix(cvr, delete): add finalizer to reclaim space on volume delete
  cmd/cstor-pool-mgmt/controller/common/common.go
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: BUG, component: CStorPoolMgmt, component: CStorVolMgmt, needs-upgrade-changes, type: CherryPick-To-1.0.x

#1258 fix(bdd,exporter): rename metrics name
  tests/exporter/exporter_test.go
Labels: component: Exporter, component: IntegrationTests, type: BDD

#1260 cherrypick(fix, cvr, delete): add finalizer to reclaim space on volume delete
  cmd/cstor-pool-mgmt/controller/common/common.go
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: BUG, component: CStorPoolMgmt, component: CStorVolMgmt, needs-upgrade-changes, type: CASTemplate

#1261 cherry-pick(bdd,exporter): rename metrics name (#1258)
  tests/exporter/exporter_test.go
Labels: component: IntegrationTests, type: BDD

#1262 fix(localpv): handle case of BDC-BD taking longer time
  cmd/provisioner-localpv/app/helper_blockdevice.go
Labels: BUG, component: LocalPV

#1254 refact(bdd, jiva) added data consistency check for clone creation BDD
  pkg/kubernetes/pod/v1alpha1/build.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/pod.go
  tests/jiva/clone/provision_test.go
  tests/operations.go
Labels: component: IntegrationTests, component: Jiva, type: BDD

#1263 fix(cvr, delete): ensure cvr gets deleted during reconcile
  cmd/cstor-pool-mgmt/controller/common/common.go
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-pool-mgmt/controller/replica-controller/new_replica_controller.go
  cmd/cstor-pool-mgmt/controller/replica-controller/run_replica_controller.go
Labels: BUG, component: CStorPoolMgmt, component: CStorVolMgmt

#1264 refact(cstor-pool,sparse): Update SPC type to blockdevice
  pkg/install/v1alpha1/cstor_sparse_pool_claim.go
Labels: component: CStorOperator, component: NDM, needs-upgrade-changes, type: CherryPick-To-1.0.x, type: Documentation

#1255 feat(cstor-operator): add a support to create pools on unclaimed BD in manual mode
  cmd/maya-apiserver/cstor-operator/spc/handler_test.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/blockdevice/v1alpha1/blockdevice.go
  pkg/blockdevice/v1alpha1/blockdevice_test.go
  pkg/blockdevice/v1alpha1/kubernetes_client.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
  pkg/blockdeviceclaim/v1alpha1/build.go
  pkg/blockdeviceclaim/v1alpha1/build_test.go
  pkg/blockdeviceclaim/v1alpha1/buildlist.go
  pkg/blockdeviceclaim/v1alpha1/buildlist_test.go
  pkg/blockdeviceclaim/v1alpha1/kubernetes.go
  pkg/blockdeviceclaim/v1alpha1/kubernetes_test.go
  pkg/volume/rounding.go
  pkg/volume/rounding_test.go
Labels: component: CStorOperator, component: NDM

#1270 [cherry-pick] fix(blockdeviceclaims): fix openebs version type in blockdeviceclaim
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/blockdeviceclaim/v1alpha1/build.go
Labels: needs-upgrade-changes

#1271 refact(bdd, jiva) added target affinity check after controller and replica pods restart
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
  pkg/kubernetes/pod/v1alpha1/kubernetes_test.go
  tests/jiva/clone/provision_test.go
  tests/jiva/volume/provision_test.go
  tests/jiva/volume/suite_test.go
Labels: component: IntegrationTests, component: Jiva, type: BDD

#1275 chore(cstor-operator): update cspc schema
  pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolcluster.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolcluster_test.go
  pkg/cstorpoolcluster/v1alpha1/doc.go
  pkg/cstorpoolcluster/v1alpha1/kubernetes.go
  pkg/cstorpoolcluster/v1alpha1/validate.go
Labels: component: CStorOperator, needs-upgrade-changes, release-note

#1272 feat(bdd, localpv) add BDD for localpv provisioning using hostdevice
  pkg/kubernetes/deployment/appsv1/v1alpha1/deployment.go
  tests/kubernetes/deployment/app_test.go
  tests/localpv/hostdevice_test.go
  tests/localpv/hostpath_test.go
  tests/localpv/suite_test.go
Labels: component: IntegrationTests, type: BDD

#1274 feat(cstor-operator, blockdevice): add support to create cStor pools on unclaimed BD in auto mode
  cmd/maya-apiserver/cstor-operator/spc/handler.go
  cmd/maya-apiserver/cstor-operator/spc/handler_test.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
  pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
  pkg/blockdevice/v1alpha1/blockdevice.go
  pkg/blockdevice/v1alpha1/blockdevice_test.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
  pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
Labels: component: CStorOperator, component: NDM, type: Documentation

#1278 [cherry-pick] feat(cstor-operator, blockdevice): add support to create cStor pools on unclaimed BD in auto mode
  cmd/maya-apiserver/cstor-operator/spc/handler.go
  cmd/maya-apiserver/cstor-operator/spc/handler_test.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
  pkg/algorithm/nodeselect/v1alpha1/select_node.go
  pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
  pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
  pkg/blockdevice/v1alpha1/blockdevice.go
  pkg/blockdevice/v1alpha1/blockdevice_test.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim.go
  pkg/blockdeviceclaim/v1alpha1/blockdeviceclaim_test.go
  pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
Labels: component: CStorOperator, type: Documentation

#1279 feat(bdd, cstor) BDD for provisioning volume without disk
  pkg/blockdevice/v1alpha2/kubernetes.go
  tests/cstor/pool/negative/provision_without_disk_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD

#1276 bdd(pvc, cstor): add bulk create and delete of pvcs in a given namespace
  GNUmakefile
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/build.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/build_test.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/buildlist.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes.go
  pkg/kubernetes/persistentvolumeclaim/v1alpha1/kubernetes_test.go
  tests/cstor/volume/provision_bulk_test.go
  tests/exporter/exporter_test.go
Labels: component: IntegrationTests, type: BDD

#1277 feat(bdd,cstor): enhance cstor volume data integrity tests
  tests/cstor/clone/clone_test.go
  tests/cstor/clone/suite_test.go
Labels: component: IntegrationTests, type: BDD

#1284 refact(cstor-pool,sparse): Update SPC type to sparse
  pkg/install/v1alpha1/cstor_sparse_pool_claim.go
Labels: component: CStorOperator, component: NDM, needs-upgrade-changes, type: CherryPick-To-1.0.x

#1282 refact(bdc,ndm): use storage in BDC request instead of capacity
  pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
  pkg/apis/openebs.io/ndm/v1alpha1/zz_generated.deepcopy.go
  pkg/blockdeviceclaim/v1alpha1/build.go
  pkg/blockdeviceclaim/v1alpha1/build_test.go
Labels: component: CStorOperator, component: NDM

#1280 feat[cstor-operator, cstor-pool-mgmt, upgrade]: add support to stop reconciliation during upgrade
  cmd/cstor-pool-mgmt/controller/pool-controller/new_pool_controller.go
  cmd/maya-apiserver/cstor-operator/spc/controller.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
Labels: component: CStorOperator, component: CStorPoolMgmt, component: Upgrade, type: CherryPick-To-1.0.x

#1283 feat(localpv): allow creating Local PV on unformatted devices
  cmd/provisioner-localpv/app/config.go
  cmd/provisioner-localpv/app/doc.go
  cmd/provisioner-localpv/app/helper_hostpath.go
  cmd/provisioner-localpv/app/provisioner_blockdevice.go
  pkg/kubernetes/persistentvolume/v1alpha1/build.go
  pkg/kubernetes/persistentvolume/v1alpha1/build_test.go
Labels: component: LocalPV, type: CherryPick-To-1.0.x

#1289 feat(usage) Initial code to send localpv analytics
  cmd/provisioner-localpv/app/provisioner.go
  pkg/usage/const.go
Labels: component: LocalPV, type: Analytics

#1286 feat(cordon,taint): add builder pattern for node taint and cordon
  Gopkg.lock
  pkg/kubernetes/node/v1alpha1/kubernetes.go
  pkg/kubernetes/node/v1alpha1/kubernetes_test.go
  pkg/kubernetes/node/v1alpha1/node.go
  pkg/kubernetes/node/v1alpha1/node_test.go
Labels: type: IdiomaticMaya

#1300 refact(cstor,BDD): verify cvr destroy event reconciliation via deleting pools pods
  tests/cstor/volume/provision_bulk_test.go
  tests/cstor/volume/provision_test.go
  tests/operations.go
Labels: component: IntegrationTests, type: BDD

#1302 fix(apis): change ndm apis
  pkg/apis/openebs.io/ndm/v1alpha1/blockdevice_types.go
  pkg/apis/openebs.io/ndm/v1alpha1/blockdeviceclaim_types.go
Labels: component: CStorPoolMgmt, component: NDM

#1306 feat(cstor-operator): move CSPC to namespace scope
  pkg/apis/openebs.io/v1alpha1/cstorpool_cluster.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/cstorpoolcluster.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_cstorpoolcluster.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/fake/fake_openebs.io_client.go
  pkg/client/generated/clientset/versioned/typed/openebs.io/v1alpha1/openebs.io_client.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/cstorpoolcluster.go
  pkg/client/generated/informers/externalversions/openebs.io/v1alpha1/interface.go
  pkg/client/generated/listers/openebs.io/v1alpha1/cstorpoolcluster.go
  pkg/client/generated/listers/openebs.io/v1alpha1/expansion_generated.go
  pkg/client/k8s/k8s.go
  pkg/install/v1alpha1/openebs_crds.go
Labels: component: CStorOperator, needs-review, needs-upgrade-changes, release-note, type: CodeGen

#1290 feat(cstor-operator): add cstorpoolcluster package
  pkg/cstorpoolcluster/v1alpha1/build.go
  pkg/cstorpoolcluster/v1alpha1/build_test.go
  pkg/cstorpoolcluster/v1alpha1/buildlist.go
  pkg/cstorpoolcluster/v1alpha1/buildlist_test.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolcluster.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolcluster_test.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolspecs/build.go
  pkg/cstorpoolcluster/v1alpha1/cstorpoolspecs/cstorpoolspecs.go
  pkg/cstorpoolcluster/v1alpha1/kubernetes.go
  pkg/cstorpoolcluster/v1alpha1/kubernetes_test.go
  pkg/cstorpoolcluster/v1alpha1/raidgroups/build.go
  pkg/cstorpoolcluster/v1alpha1/raidgroups/raidgroups.go
Labels: component: CStorOperator, needs-review, needs-upgrade-changes, release-note

#1237 refactor(k8s, client): update kubernetes client as per idiomatic maya
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/client/v1alpha1/client_test.go
  pkg/kubernetes/pod/v1alpha1/kubernetes.go
Labels: type: IdiomaticMaya

#1318 refactor(k8s client): update k8s packages based on idiomatic maya
  pkg/kubernetes/client/v1alpha1/client.go
  pkg/kubernetes/deployment/appsv1/v1alpha1/kubernetes.go
Labels: type: IdiomaticMaya

#1317 feat(builder) added builder pattern for service object
  pkg/kubernetes/service/v1alpha1/build.go
  pkg/kubernetes/service/v1alpha1/kubernetes.go
  pkg/kubernetes/service/v1alpha1/service.go
  pkg/task/task.go
Labels: type: IdiomaticMaya

#1315 refact(BDD, cstor) added cleanup after each test in csp reconciliation test
  tests/cstor-pool/README.md
  tests/cstor/pool/reconciliation/reconciliation_test.go
  tests/cstor/pool/reconciliation/suite_test.go
Labels: component: IntegrationTests, type: BDD

#1319 feat(builder) added builder pattern for cstorvolume
  pkg/cstorvolume/v1alpha1/build.go
  pkg/cstorvolume/v1alpha1/build_test.go
  pkg/cstorvolume/v1alpha1/kubernetes.go
  pkg/cstorvolume/v1alpha1/kubernetes_test.go
Labels: type: IdiomaticMaya

#1322 chore(packaging): move cstor related packages within cstor package
  cmd/cstor-volume-mgmt/app/command/start.go
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create_test.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
  pkg/algorithm/nodeselect/v1alpha1/config.go
  pkg/algorithm/nodeselect/v1alpha1/select_node_test.go
  pkg/cstor/pool/v1alpha1/cstorpool.go
  pkg/cstor/pool/v1alpha1/kubernetes_client.go
  pkg/cstor/pool/v1alpha1/kubernetes_client_test.go
  pkg/cstor/pool/v1alpha2/cstorpool.go
  pkg/cstor/pool/v1alpha2/cstorpool_test.go
  pkg/cstor/pool/v1alpha2/doc.go
  pkg/cstor/pool/v1alpha2/kubernetes.go
  pkg/cstor/pool/v1alpha2/kubernetes_test.go
  pkg/cstor/pool/v1alpha3/cstorpool.go
  pkg/cstor/pool/v1alpha3/cstorpool_test.go
  pkg/cstor/pool/v1alpha3/doc.go
  pkg/cstor/pool/v1alpha3/kubernetes.go
  pkg/cstor/poolcluster/v1alpha1/build.go
  pkg/cstor/poolcluster/v1alpha1/build_test.go
  pkg/cstor/poolcluster/v1alpha1/buildlist.go
  pkg/cstor/poolcluster/v1alpha1/buildlist_test.go
  pkg/cstor/poolcluster/v1alpha1/cstorpoolcluster.go
  pkg/cstor/poolcluster/v1alpha1/cstorpoolcluster_test.go
  pkg/cstor/poolcluster/v1alpha1/cstorpoolspecs/build.go
  pkg/cstor/poolcluster/v1alpha1/cstorpoolspecs/cstorpoolspecs.go
  pkg/cstor/poolcluster/v1alpha1/kubernetes.go
  pkg/cstor/poolcluster/v1alpha1/kubernetes_test.go
  pkg/cstor/poolcluster/v1alpha1/raidgroups/build.go
  pkg/cstor/poolcluster/v1alpha1/raidgroups/raidgroups.go
  pkg/cstor/volume/serverclient/v1alpha1/api.go
  pkg/cstor/volume/serverclient/v1alpha1/api_test.go
  pkg/cstor/volume/serverclient/v1alpha1/server.go
  pkg/cstor/volume/v1alpha1/build.go
  pkg/cstor/volume/v1alpha1/build_test.go
  pkg/cstor/volume/v1alpha1/cstorvolume.go
  pkg/cstor/volume/v1alpha1/cstorvolume_test.go
  pkg/cstor/volume/v1alpha1/kubernetes.go
  pkg/cstor/volume/v1alpha1/kubernetes_test.go
  pkg/cstor/volumereplica/v1alpha1/build.go
  pkg/cstor/volumereplica/v1alpha1/build_test.go
  pkg/cstor/volumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstor/volumereplica/v1alpha1/cstorvolumereplica_test.go
  pkg/cstor/volumereplica/v1alpha1/kubernetes.go
  pkg/cstor/volumereplica/v1alpha1/kubernetes_test.go
  pkg/task/task.go
  pkg/templatefuncs/v1alpha1/templatefuncs.go
  tests/exporter/exporter_test.go
  tests/operations.go
  tests/sts/sts_test.go
Labels: type: IdiomaticMaya
