Repository openebs/maya, pull requests merged in 2019-02, with the labels that each got.

#934 enhance(Runtask): Remove hardcoding of jiva delete scrub image
  pkg/install/v1alpha1/jiva_volume.go
Labels: area/documentation

#936 enhance(Runtask): Remove hardcoding of jiva delete scrub image
  pkg/install/v1alpha1/jiva_volume.go
Labels: area/documentation

#932 Implements a packge to calculate hash for given objects
  pkg/hash/v1alpha1/hash.go
  pkg/hash/v1alpha1/hash_test.go
Labels: Needs-Review, area/maya

#872 enhance(StoragePool): add owner references to StoragePool related CRs for garbage collection
  pkg/install/v1alpha1/cstor_pool.go
Labels: Needs-Review, WIP, area/maya, release-note

#931 enhance(BDD): Add BDD test to fetch version of kubernetes
  integration-tests/kubernetes/kubeclient.go
  integration-tests/kubernetes/kubernetes_suite_test.go
  integration-tests/kubernetes/kubernetes_test.go
Labels: BDD

#933 enhance(BDD): adds sanity package in BDD Test
  integration-tests/sanity/sanity_suite_test.go
  integration-tests/sanity/sanity_test.go
Labels: BDD

#938 cleanup(CAS Template): remove cStor delete cas templates
  cmd/maya-apiserver/cstor-operator/controller.go
  cmd/maya-apiserver/cstor-operator/controller_test.go
  cmd/maya-apiserver/cstor-operator/handler.go
  cmd/maya-apiserver/cstor-operator/handler_test.go
  cmd/maya-apiserver/cstor-operator/storagepool_delete.go
  pkg/install/v1alpha1/cstor_pool.go
Labels: Needs-Review, area/cstor-operator, area/maya

#953 fix(mayactl): fixes application name & namespace not available during a volume describe
  pkg/install/v1alpha1/cstor_volume.go
Labels: cherrypick-to-0.8.x, needs-upgrade

#950 feat(volume distribution, cstor replica, pool anti-affinity): adds support to distribute data across cstor storagepools
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
  pkg/cstorpool/v1alpha2/cstorpool.go
  pkg/cstorpool/v1alpha2/cstorpool_test.go
  pkg/cstorpool/v1alpha2/doc.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica.go
  pkg/cstorvolumereplica/v1alpha1/cstorvolumereplica_test.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/template/template.go
Labels: app/statefulset, area/cstor-vol-mgmt

#954 fix(travis): updates invalid UT testcase
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
Labels: cherrypick-to-0.8.x, release-note-none

#956 refactor(select.go): Adds unit test for untested functions
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
  pkg/cstorpool/v1alpha2/cstorpool_test.go
  pkg/cstorvolumereplica/v1alpha1/kubernetes_test.go
Labels: cherrypick-to-0.8.x, release-note-none

#955 fix(cvr delete, finalizer): remove finalizers to ensure successful deletion
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: area/cstor-vol-mgmt, cherrypick-to-0.8.x, needs-upgrade
