Repository openebs/maya, pull requests merged in 2019-11, with the labels that each got.

#1502 Update README.md
  README.md
Labels: Hacktoberfest

#1495 CONTRIBUTING.md: Fix typo of `familiar`
  CONTRIBUTING.md
Labels: Hacktoberfest

#1497 refactor helper_hostpath.go
  cmd/provisioner-localpv/app/helper_hostpath.go
Labels: Hacktoberfest

#1499 feat(cstor-volume-mgmt): add replica scale down support
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  cmd/cstor-volume-mgmt/controller/volume-controller/handler.go
  cmd/cstor-volume-mgmt/controller/volume-controller/new_volume_controller.go
  cmd/cstor-volume-mgmt/volume/volume.go
  cmd/cstor-volume-mgmt/volume/volume_test.go
  pkg/cstor/volume/v1alpha1/cstorvolume.go
  pkg/util/fileoperator.go
  pkg/util/fileoperator_test.go
Labels: auto-scale, component: CStorVolMgmt, release-note

#1514 chore(CVR status): add CVR phases based on scenarios
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica_test.go
  cmd/upgrade/executor/cstor_spc.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
Labels: release-note

#1525 fix(cStorVolumeReplica): reconciliation logic for volume replica creation failures
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
Labels: release-note

#1538 fix(tools): set default helper pod image to latest
  cmd/provisioner-localpv/app/env.go
  pkg/install/v1alpha1/jiva_volume.go
Labels: release-note
