Repository openebs/maya, pull requests merged in 2020-04, with the labels that each got.

#1641 feat(pendingsnapshots): add pending snapshots on CVR by talking to peer replicas
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
Labels: pr/ready-to-merge

#1640 chore(BDD): Add checks to verify pool protection finalizer on CSP
  tests/cstor/pool/reconciliation/reconciliation_test.go
  tests/operations.go
Labels: pr/ready-to-merge, type: BDD

#1645 fix(jiva): add namespace to podAffinity for target
  pkg/install/v1alpha1/jiva_volume.go
Labels: kind/bug-fix

#1643 feat(BDD): add positive test cases for verifying waitforfirstconsumer With CStor Volume Provisioning
  pkg/kubernetes/pod/v1alpha1/buildlist.go
  pkg/kubernetes/pod/v1alpha1/buildlist_test.go
  pkg/kubernetes/pod/v1alpha1/pod.go
  pkg/kubernetes/storageclass/v1alpha1/build.go
  pkg/kubernetes/storageclass/v1alpha1/build_test.go
  tests/cstor/volume/provision_test.go
  tests/cstor/volume/suite_test.go
  tests/cstor/volume/waitforfirstconsumer_test.go
  tests/operations.go
Labels: status/ready-for-review, type: BDD

#1648 feat(localpv-device): allow local pv device on select devices
  cmd/provisioner-localpv/app/config.go
  cmd/provisioner-localpv/app/helper_blockdevice.go
  cmd/provisioner-localpv/app/provisioner_blockdevice.go
  pkg/blockdeviceclaim/v1alpha1/build.go
  pkg/blockdeviceclaim/v1alpha1/build_test.go
  tests/localpv/README.md
  tests/localpv/suite_test.go
Labels: pr/documentation-pending, pr/release-note

#1655 feat(upgrade): enable bulk upgrade for volumes and spc
  cmd/upgrade/executor/cstor_spc.go
  cmd/upgrade/executor/cstor_volume.go
  cmd/upgrade/executor/jiva_volume.go
Labels: pr/documentation-pending, pr/release-note

#1662 fix(localpv-hostpath):pv deletion caused panic, if node not found
  cmd/provisioner-localpv/app/provisioner_hostpath.go
Labels: pr/release-note

#1664 fix(localpv-hostpath): pv deletion caused panic when node not found
  cmd/provisioner-localpv/app/provisioner_hostpath.go
Labels: pr/release-note

#1660 chore(build): update alpine base images to 3.11.5
  buildscripts/apiserver/Dockerfile
  buildscripts/cspc-operator-debug/Dockerfile
  buildscripts/cspc-operator/Dockerfile
  buildscripts/cvc-operator/Dockerfile
  buildscripts/mayactl/Dockerfile
  buildscripts/openebs-cluster/Dockerfile
  buildscripts/provisioner-localpv/Dockerfile
  buildscripts/upgrade/Dockerfile
Labels: pr/hold-merge

#1656 chore(CHANGELOG): add changelog for v1.9.0
  CHANGELOG.md
Labels: pr/hold-merge, type: Documentation

#1670 chore(CVR): enable REBUILD_ESTIMATES feature gate
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
  cmd/cstor-pool-mgmt/volumereplica/volumereplica.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_replica.go
Labels: pr/ready-to-merge, pr/release-note

#1674 chore(doc): add unreleased changelogs in repo
  changelogs/unreleased/1670-mittachaitu
  changelogs/unreleased/1699-mittachaitu
Labels: needs-review

#1675 fix(cStorvolumereplica): record the error while fetching the snapshot information
  cmd/cstor-pool-mgmt/controller/replica-controller/handler.go
Labels: needs-review
