Repository openebs/maya, pull requests merged in 2020-01, with the labels that each got.

#1543 chore(cspc, validation webhook): add a support for CSPC general validation in admission server
  cmd/cstor-pool-mgmt/pool/v1alpha2/modify.go
  cmd/cstor-pool-mgmt/pool/v1alpha2/pool_utils.go
  pkg/algorithm/nodeselect/v1alpha2/build_csp.go
  pkg/algorithm/nodeselect/v1alpha2/select_node.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/blockdevice/v1alpha2/blockdevice.go
  pkg/blockdevice/v1alpha2/blockdevice_test.go
  pkg/webhook/bd_replacement.go
  pkg/webhook/bd_replacement_test.go
  pkg/webhook/cspc.go
  pkg/webhook/cspc_test.go
Labels: component: admission-server, needs-review

#1560 feat(localpv-hostpath): support provisioning on nodes with taints
  cmd/provisioner-localpv/app/config.go
  cmd/provisioner-localpv/app/helper_hostpath.go
  cmd/provisioner-localpv/app/provisioner_hostpath.go
  pkg/kubernetes/pod/v1alpha1/build.go
Labels: component: LocalPV, release-note

#1581 feat(localpv-hostpath): support provisioning on nodes with taints (#1560)
  cmd/provisioner-localpv/app/config.go
  cmd/provisioner-localpv/app/helper_hostpath.go
  cmd/provisioner-localpv/app/provisioner_hostpath.go
  pkg/kubernetes/pod/v1alpha1/build.go
Labels: component: LocalPV, type: CherryPicked

#1583 fix(cStor, deployments): add OpenEBS base directory in deployments
  pkg/install/v1alpha1/cstor_pool.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: needs-upgrade-changes

#1577 feat(spc): add feature to limit overprovisioning of cstor volumes
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/algorithm/cstorpoolselect/v1alpha1/select_test.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/cstor/pool/v1alpha2/cstorpool.go
  pkg/cstor/pool/v1alpha2/cstorpool_test.go
  pkg/install/v1alpha1/cstor_volume.go
  pkg/storagepoolclaim/v1alpha1/storagepoolclaim.go
Labels: needs-review, release-note

#1589 fix(cStor, deployments): update mount paths in cStor deployments
  pkg/install/v1alpha1/cstor_pool.go
  pkg/install/v1alpha1/cstor_volume.go
Labels: needs-upgrade-changes

#1579 fix(cspc): cleanup bdcs after deletion or scaledown of cspi
  cmd/cspc-operator/app/cleanup.go
  cmd/cspc-operator/app/handler.go
  cmd/cspi-mgmt/app/handler.go
  pkg/cstor/poolcluster/v1alpha1/cstorpoolcluster.go
  tests/cstor/cspc/provisioning/cspc_provisioning_utils_test.go
  tests/cstor/cspc/provisioning/provisioning_test.go
  tests/operations.go
Labels: enhancement, needs-review

#1573 feat(PDB, cStor Pools): add a support to create PDB for cStor
  Gopkg.lock
  cmd/cspc-operator/app/storagepool_create.go
  cmd/cvc-operator/controller/cstorvolumeclaim.go
  cmd/cvc-operator/controller/cvc_controller.go
  cmd/cvc-operator/controller/start.go
  pkg/apis/openebs.io/v1alpha1/cas_keys.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/cstor/volumereplica/v1alpha1/utils.go
  pkg/cstorvolumeclaim/v1alpha1/utils.go
  pkg/hash/hash_test.go
  pkg/kubernetes/poddisruptionbudget/kubernetes.go
  pkg/kubernetes/poddisruptionbudget/poddisruptionbudget.go
Labels: needs-review, release-note

#1597 chore(spc):introduce new field to control overprovisioning
  pkg/algorithm/cstorpoolselect/v1alpha1/select.go
  pkg/apis/openebs.io/v1alpha1/cstor_pool.go
Labels: release-note

#1591 feat(cvc,csi): pre provisioning and prioritize pool for replica scheduling
  cmd/cvc-operator/controller/cstorvolumeclaim.go
  cmd/cvc-operator/controller/cvc_controller.go
  pkg/algorithm/nodeselect/v1alpha2/select_node.go
  pkg/apis/openebs.io/v1alpha1/cstor_volume_claim.go
  pkg/apis/openebs.io/v1alpha1/cstorvolume_policy.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
Labels: component: CSI, component: CStorOperator
