Repository openebs/maya, pull requests merged in 2020-03, with the labels that each got.

#1623 feat(csp, poolROThreshold): setting pool ReadOnly Threshold limit default to 85
  cmd/maya-apiserver/cstor-operator/spc/storagepool_create.go
Labels: needs-upgrade-changes

#1635 fix(csp): add pool protection finalizer on CSP
  cmd/cstor-pool-mgmt/controller/pool-controller/handler.go
  pkg/apis/openebs.io/v1alpha1/cas_pool.go
  pkg/upgrade/templates/v1/cstor_pool.go
  pkg/upgrade/upgrader/csp_upgrade.go
Labels: BUG, component: CStorPoolMgmt

#1637 fix(provisioning): support to provision volumes in case of WaitForFirstConsumer
  pkg/install/v1alpha1/cstor_volume.go
Labels: pr/release-note

#1638 refact(log): remove cstor prefix from localPV log and alert messages
  cmd/provisioner-localpv/app/provisioner.go
  cmd/provisioner-localpv/app/provisioner_blockdevice.go
  cmd/provisioner-localpv/app/provisioner_hostpath.go
Labels: pr/release-note-none

#1575 feat(local-snapshot-restore, velero) : support to restore local snapshot to different namespace using velero
  cmd/maya-apiserver/app/server/backup_endpoint_v1alpha1.go
  cmd/maya-apiserver/app/server/restore_endpoint_v1alpha1.go
  cmd/maya-apiserver/app/server/volume_endpoint_v1alpha1.go
  pkg/apis/openebs.io/v1alpha1/cstor_backup.go
  pkg/apis/openebs.io/v1alpha1/cstor_restore.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
Labels: pr/documentation-pending, pr/hold-merge, pr/release-note

#1636 refact(jiva): create separate replica deployments and move all resources to openebsNamespace
  ci/mayactl.sh
  pkg/install/v1alpha1/jiva_volume.go
  pkg/templatefuncs/v1alpha1/runtask_functions.go
Labels: pr/documentation-pending, pr/hold-review, pr/release-note, pr/upgrade-pending
